// https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html

export const AwsEc2ManagedMetricNames = {
  CPU_UTILIZATION: "CPUUtilization",
  DISK_READ_OPS: "DiskReadOps",
  DISK_WRITE_OPS: "DiskWriteOps",
  DISK_READ_BYTES: "DiskReadBytes",
  DISK_WRITE_BYTES: "DiskWriteBytes",
  NETWORK_IN: "NetworkIn",
  NETWORK_OUT: "NetworkOut",
  NETWORK_PACKETS_IN: "NetworkPacketsIn",
  NETWORK_PACKETS_OUT: "NetworkPacketsOut",
  METADATA_NO_TOKEN: "MetadataNoToken",
  CPU_CREDIT_USAGE: "CPUCreditUsage",
  CPU_CREDIT_BALANCE: "CPUCreditBalance",
  CPU_SURPLUS_CREDIT_BALANCE: "CPUSurplusCreditBalance",
  CPU_SURPLUS_CREDITS_CHARGED: "CPUSurplusCreditsCharged",
  EBS_READ_OPS: "EBSReadOps",
  EBS_WRITE_OPS: "EBSWriteOps",
  EBS_READ_BYTES: "EBSReadBytes",
  EBS_WRITE_BYTES: "EBSWriteBytes",
  EBS_IO_BALANCE: "EBSIOBalance%",
  EBS_BYTE_BALANCE: "EBSByteBalance%",
  STATUS_CHECK_FAILED: "StatusCheckFailed",
  STATUS_CHECK_FAILED_INSTANCE: "StatusCheckFailed_Instance",
  STATUS_CHECK_FAILED_SYSTEM: "StatusCheckFailed_System",
  RESOURCE_COUNT: "ResourceCount",
};

/**
 * @deprecated Use AwsEc2ManagedMetricNames instead.
 */
export const Ec2ManagedMetricNames = AwsEc2ManagedMetricNames;

export const AwsEc2ManagedMetricDimensionNames = {
  AUTO_SCALING_GROUP_NAME: "AutoScalingGroupName",
  IMAGE_ID: "ImageId",
  INSTANCE_ID: "InstanceId",
  INSTANCE_TYPE: "InstanceType",
  SERVICE: "Service",
  TYPE: "Type",
  RESOURCE: "Resource",
  CLASS: "Class",
};

/**
 * @deprecated Use AwsEc2ManagedMetricDimensionNames instead.
 */
export const Ec2ManagedMetricDimensionNames = AwsEc2ManagedMetricDimensionNames;

// https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html

export const AwsEc2IamPolicyActions = {
  ACCEPT_RESERVED_INSTANCES_EXCHANGE_QUOTE:
    "AcceptReservedInstancesExchangeQuote",
  ACCEPT_TRANSIT_GATEWAY_MULTICAST_DOMAIN_ASSOCIATIONS:
    "AcceptTransitGatewayMulticastDomainAssociations",
  ACCEPT_TRANSIT_GATEWAY_PEERING_ATTACHMENT:
    "AcceptTransitGatewayPeeringAttachment",
  ACCEPT_TRANSIT_GATEWAY_VPC_ATTACHMENT: "AcceptTransitGatewayVpcAttachment",
  ACCEPT_VPC_ENDPOINT_CONNECTIONS: "AcceptVpcEndpointConnections",
  ACCEPT_VPC_PEERING_CONNECTION: "AcceptVpcPeeringConnection",
  ADVERTISE_BYOIP_CIDR: "AdvertiseByoipCidr",
  ALLOCATE_ADDRESS: "AllocateAddress",
  ALLOCATE_HOSTS: "AllocateHosts",
  APPLY_SECURITY_GROUPS_TO_CLIENT_VPN_TARGET_NETWORK:
    "ApplySecurityGroupsToClientVpnTargetNetwork",
  ASSIGN_IPV6_ADDRESSES: "AssignIpv6Addresses",
  ASSIGN_PRIVATE_IP_ADDRESSES: "AssignPrivateIpAddresses",
  ASSOCIATE_ADDRESS: "AssociateAddress",
  ASSOCIATE_CLIENT_VPN_TARGET_NETWORK: "AssociateClientVpnTargetNetwork",
  ASSOCIATE_DHCP_OPTIONS: "AssociateDhcpOptions",
  ASSOCIATE_ENCLAVE_CERTIFICATE_IAM_ROLE: "AssociateEnclaveCertificateIamRole",
  ASSOCIATE_IAM_INSTANCE_PROFILE: "AssociateIamInstanceProfile",
  ASSOCIATE_ROUTE_TABLE: "AssociateRouteTable",
  ASSOCIATE_SUBNET_CIDR_BLOCK: "AssociateSubnetCidrBlock",
  ASSOCIATE_TRANSIT_GATEWAY_MULTICAST_DOMAIN:
    "AssociateTransitGatewayMulticastDomain",
  ASSOCIATE_TRANSIT_GATEWAY_ROUTE_TABLE: "AssociateTransitGatewayRouteTable",
  ASSOCIATE_VPC_CIDR_BLOCK: "AssociateVpcCidrBlock",
  ATTACH_CLASSIC_LINK_VPC: "AttachClassicLinkVpc",
  ATTACH_INTERNET_GATEWAY: "AttachInternetGateway",
  ATTACH_NETWORK_INTERFACE: "AttachNetworkInterface",
  ATTACH_VOLUME: "AttachVolume",
  ATTACH_VPN_GATEWAY: "AttachVpnGateway",
  AUTHORIZE_CLIENT_VPN_INGRESS: "AuthorizeClientVpnIngress",
  AUTHORIZE_SECURITY_GROUP_EGRESS: "AuthorizeSecurityGroupEgress",
  AUTHORIZE_SECURITY_GROUP_INGRESS: "AuthorizeSecurityGroupIngress",
  BUNDLE_INSTANCE: "BundleInstance",
  CANCEL_BUNDLE_TASK: "CancelBundleTask",
  CANCEL_CAPACITY_RESERVATION: "CancelCapacityReservation",
  CANCEL_CONVERSION_TASK: "CancelConversionTask",
  CANCEL_EXPORT_TASK: "CancelExportTask",
  CANCEL_IMPORT_TASK: "CancelImportTask",
  CANCEL_RESERVED_INSTANCES_LISTING: "CancelReservedInstancesListing",
  CANCEL_SPOT_FLEET_REQUESTS: "CancelSpotFleetRequests",
  CANCEL_SPOT_INSTANCE_REQUESTS: "CancelSpotInstanceRequests",
  CONFIRM_PRODUCT_INSTANCE: "ConfirmProductInstance",
  COPY_FPGA_IMAGE: "CopyFpgaImage",
  COPY_IMAGE: "CopyImage",
  COPY_SNAPSHOT: "CopySnapshot",
  CREATE_CAPACITY_RESERVATION: "CreateCapacityReservation",
  CREATE_CARRIER_GATEWAY: "CreateCarrierGateway",
  CREATE_CLIENT_VPN_ENDPOINT: "CreateClientVpnEndpoint",
  CREATE_CLIENT_VPN_ROUTE: "CreateClientVpnRoute",
  CREATE_CUSTOMER_GATEWAY: "CreateCustomerGateway",
  CREATE_DEFAULT_SUBNET: "CreateDefaultSubnet",
  CREATE_DEFAULT_VPC: "CreateDefaultVpc",
  CREATE_DHCP_OPTIONS: "CreateDhcpOptions",
  CREATE_EGRESS_ONLY_INTERNET_GATEWAY: "CreateEgressOnlyInternetGateway",
  CREATE_FLEET: "CreateFleet",
  CREATE_FLOW_LOGS: "CreateFlowLogs",
  CREATE_FPGA_IMAGE: "CreateFpgaImage",
  CREATE_IMAGE: "CreateImage",
  CREATE_INSTANCE_EXPORT_TASK: "CreateInstanceExportTask",
  CREATE_INTERNET_GATEWAY: "CreateInternetGateway",
  CREATE_KEY_PAIR: "CreateKeyPair",
  CREATE_LAUNCH_TEMPLATE: "CreateLaunchTemplate",
  CREATE_LAUNCH_TEMPLATE_VERSION: "CreateLaunchTemplateVersion",
  CREATE_LOCAL_GATEWAY_ROUTE: "CreateLocalGatewayRoute",
  CREATE_LOCAL_GATEWAY_ROUTE_TABLE_VPC_ASSOCIATION:
    "CreateLocalGatewayRouteTableVpcAssociation",
  CREATE_MANAGED_PREFIX_LIST: "CreateManagedPrefixList",
  CREATE_NAT_GATEWAY: "CreateNatGateway",
  CREATE_NETWORK_ACL: "CreateNetworkAcl",
  CREATE_NETWORK_ACL_ENTRY: "CreateNetworkAclEntry",
  CREATE_NETWORK_INSIGHTS_PATH: "CreateNetworkInsightsPath",
  CREATE_NETWORK_INTERFACE: "CreateNetworkInterface",
  CREATE_NETWORK_INTERFACE_PERMISSION: "CreateNetworkInterfacePermission",
  CREATE_PLACEMENT_GROUP: "CreatePlacementGroup",
  CREATE_RESERVED_INSTANCES_LISTING: "CreateReservedInstancesListing",
  CREATE_ROUTE: "CreateRoute",
  CREATE_ROUTE_TABLE: "CreateRouteTable",
  CREATE_SECURITY_GROUP: "CreateSecurityGroup",
  CREATE_SNAPSHOT: "CreateSnapshot",
  CREATE_SNAPSHOTS: "CreateSnapshots",
  CREATE_SPOT_DATAFEED_SUBSCRIPTION: "CreateSpotDatafeedSubscription",
  CREATE_SUBNET: "CreateSubnet",
  CREATE_TAGS: "CreateTags",
  CREATE_TRAFFIC_MIRROR_FILTER: "CreateTrafficMirrorFilter",
  CREATE_TRAFFIC_MIRROR_FILTER_RULE: "CreateTrafficMirrorFilterRule",
  CREATE_TRAFFIC_MIRROR_SESSION: "CreateTrafficMirrorSession",
  CREATE_TRAFFIC_MIRROR_TARGET: "CreateTrafficMirrorTarget",
  CREATE_TRANSIT_GATEWAY: "CreateTransitGateway",
  CREATE_TRANSIT_GATEWAY_CONNECT: "CreateTransitGatewayConnect",
  CREATE_TRANSIT_GATEWAY_CONNECT_PEER: "CreateTransitGatewayConnectPeer",
  CREATE_TRANSIT_GATEWAY_MULTICAST_DOMAIN:
    "CreateTransitGatewayMulticastDomain",
  CREATE_TRANSIT_GATEWAY_PEERING_ATTACHMENT:
    "CreateTransitGatewayPeeringAttachment",
  CREATE_TRANSIT_GATEWAY_PREFIX_LIST_REFERENCE:
    "CreateTransitGatewayPrefixListReference",
  CREATE_TRANSIT_GATEWAY_ROUTE: "CreateTransitGatewayRoute",
  CREATE_TRANSIT_GATEWAY_ROUTE_TABLE: "CreateTransitGatewayRouteTable",
  CREATE_TRANSIT_GATEWAY_VPC_ATTACHMENT: "CreateTransitGatewayVpcAttachment",
  CREATE_VOLUME: "CreateVolume",
  CREATE_VPC: "CreateVpc",
  CREATE_VPC_ENDPOINT: "CreateVpcEndpoint",
  CREATE_VPC_ENDPOINT_CONNECTION_NOTIFICATION:
    "CreateVpcEndpointConnectionNotification",
  CREATE_VPC_ENDPOINT_SERVICE_CONFIGURATION:
    "CreateVpcEndpointServiceConfiguration",
  CREATE_VPC_PEERING_CONNECTION: "CreateVpcPeeringConnection",
  CREATE_VPN_CONNECTION: "CreateVpnConnection",
  CREATE_VPN_CONNECTION_ROUTE: "CreateVpnConnectionRoute",
  CREATE_VPN_GATEWAY: "CreateVpnGateway",
  DELETE_CARRIER_GATEWAY: "DeleteCarrierGateway",
  DELETE_CLIENT_VPN_ENDPOINT: "DeleteClientVpnEndpoint",
  DELETE_CLIENT_VPN_ROUTE: "DeleteClientVpnRoute",
  DELETE_CUSTOMER_GATEWAY: "DeleteCustomerGateway",
  DELETE_DHCP_OPTIONS: "DeleteDhcpOptions",
  DELETE_EGRESS_ONLY_INTERNET_GATEWAY: "DeleteEgressOnlyInternetGateway",
  DELETE_FLEETS: "DeleteFleets",
  DELETE_FLOW_LOGS: "DeleteFlowLogs",
  DELETE_FPGA_IMAGE: "DeleteFpgaImage",
  DELETE_INTERNET_GATEWAY: "DeleteInternetGateway",
  DELETE_KEY_PAIR: "DeleteKeyPair",
  DELETE_LAUNCH_TEMPLATE: "DeleteLaunchTemplate",
  DELETE_LAUNCH_TEMPLATE_VERSIONS: "DeleteLaunchTemplateVersions",
  DELETE_LOCAL_GATEWAY_ROUTE: "DeleteLocalGatewayRoute",
  DELETE_LOCAL_GATEWAY_ROUTE_TABLE_VPC_ASSOCIATION:
    "DeleteLocalGatewayRouteTableVpcAssociation",
  DELETE_MANAGED_PREFIX_LIST: "DeleteManagedPrefixList",
  DELETE_NAT_GATEWAY: "DeleteNatGateway",
  DELETE_NETWORK_ACL: "DeleteNetworkAcl",
  DELETE_NETWORK_ACL_ENTRY: "DeleteNetworkAclEntry",
  DELETE_NETWORK_INSIGHTS_ANALYSIS: "DeleteNetworkInsightsAnalysis",
  DELETE_NETWORK_INSIGHTS_PATH: "DeleteNetworkInsightsPath",
  DELETE_NETWORK_INTERFACE: "DeleteNetworkInterface",
  DELETE_NETWORK_INTERFACE_PERMISSION: "DeleteNetworkInterfacePermission",
  DELETE_PLACEMENT_GROUP: "DeletePlacementGroup",
  DELETE_QUEUED_RESERVED_INSTANCES: "DeleteQueuedReservedInstances",
  DELETE_ROUTE: "DeleteRoute",
  DELETE_ROUTE_TABLE: "DeleteRouteTable",
  DELETE_SECURITY_GROUP: "DeleteSecurityGroup",
  DELETE_SNAPSHOT: "DeleteSnapshot",
  DELETE_SPOT_DATAFEED_SUBSCRIPTION: "DeleteSpotDatafeedSubscription",
  DELETE_SUBNET: "DeleteSubnet",
  DELETE_TAGS: "DeleteTags",
  DELETE_TRAFFIC_MIRROR_FILTER: "DeleteTrafficMirrorFilter",
  DELETE_TRAFFIC_MIRROR_FILTER_RULE: "DeleteTrafficMirrorFilterRule",
  DELETE_TRAFFIC_MIRROR_SESSION: "DeleteTrafficMirrorSession",
  DELETE_TRAFFIC_MIRROR_TARGET: "DeleteTrafficMirrorTarget",
  DELETE_TRANSIT_GATEWAY: "DeleteTransitGateway",
  DELETE_TRANSIT_GATEWAY_CONNECT: "DeleteTransitGatewayConnect",
  DELETE_TRANSIT_GATEWAY_CONNECT_PEER: "DeleteTransitGatewayConnectPeer",
  DELETE_TRANSIT_GATEWAY_MULTICAST_DOMAIN:
    "DeleteTransitGatewayMulticastDomain",
  DELETE_TRANSIT_GATEWAY_PEERING_ATTACHMENT:
    "DeleteTransitGatewayPeeringAttachment",
  DELETE_TRANSIT_GATEWAY_PREFIX_LIST_REFERENCE:
    "DeleteTransitGatewayPrefixListReference",
  DELETE_TRANSIT_GATEWAY_ROUTE: "DeleteTransitGatewayRoute",
  DELETE_TRANSIT_GATEWAY_ROUTE_TABLE: "DeleteTransitGatewayRouteTable",
  DELETE_TRANSIT_GATEWAY_VPC_ATTACHMENT: "DeleteTransitGatewayVpcAttachment",
  DELETE_VOLUME: "DeleteVolume",
  DELETE_VPC: "DeleteVpc",
  DELETE_VPC_ENDPOINT_CONNECTION_NOTIFICATIONS:
    "DeleteVpcEndpointConnectionNotifications",
  DELETE_VPC_ENDPOINTS: "DeleteVpcEndpoints",
  DELETE_VPC_ENDPOINT_SERVICE_CONFIGURATIONS:
    "DeleteVpcEndpointServiceConfigurations",
  DELETE_VPC_PEERING_CONNECTION: "DeleteVpcPeeringConnection",
  DELETE_VPN_CONNECTION: "DeleteVpnConnection",
  DELETE_VPN_CONNECTION_ROUTE: "DeleteVpnConnectionRoute",
  DELETE_VPN_GATEWAY: "DeleteVpnGateway",
  DEPROVISION_BYOIP_CIDR: "DeprovisionByoipCidr",
  DEREGISTER_IMAGE: "DeregisterImage",
  DEREGISTER_INSTANCE_EVENT_NOTIFICATION_ATTRIBUTES:
    "DeregisterInstanceEventNotificationAttributes",
  DEREGISTER_TRANSIT_GATEWAY_MULTICAST_GROUP_MEMBERS:
    "DeregisterTransitGatewayMulticastGroupMembers",
  DEREGISTER_TRANSIT_GATEWAY_MULTICAST_GROUP_SOURCES:
    "DeregisterTransitGatewayMulticastGroupSources",
  DESCRIBE_ACCOUNT_ATTRIBUTES: "DescribeAccountAttributes",
  DESCRIBE_ADDRESSES: "DescribeAddresses",
  DESCRIBE_ADDRESSES_ATTRIBUTE: "DescribeAddressesAttribute",
  DESCRIBE_AGGREGATE_ID_FORMAT: "DescribeAggregateIdFormat",
  DESCRIBE_AVAILABILITY_ZONES: "DescribeAvailabilityZones",
  DESCRIBE_BUNDLE_TASKS: "DescribeBundleTasks",
  DESCRIBE_BYOIP_CIDRS: "DescribeByoipCidrs",
  DESCRIBE_CAPACITY_RESERVATIONS: "DescribeCapacityReservations",
  DESCRIBE_CARRIER_GATEWAYS: "DescribeCarrierGateways",
  DESCRIBE_CLASSIC_LINK_INSTANCES: "DescribeClassicLinkInstances",
  DESCRIBE_CLIENT_VPN_AUTHORIZATION_RULES:
    "DescribeClientVpnAuthorizationRules",
  DESCRIBE_CLIENT_VPN_CONNECTIONS: "DescribeClientVpnConnections",
  DESCRIBE_CLIENT_VPN_ENDPOINTS: "DescribeClientVpnEndpoints",
  DESCRIBE_CLIENT_VPN_ROUTES: "DescribeClientVpnRoutes",
  DESCRIBE_CLIENT_VPN_TARGET_NETWORKS: "DescribeClientVpnTargetNetworks",
  DESCRIBE_COIP_POOLS: "DescribeCoipPools",
  DESCRIBE_CONVERSION_TASKS: "DescribeConversionTasks",
  DESCRIBE_CUSTOMER_GATEWAYS: "DescribeCustomerGateways",
  DESCRIBE_DHCP_OPTIONS: "DescribeDhcpOptions",
  DESCRIBE_EGRESS_ONLY_INTERNET_GATEWAYS: "DescribeEgressOnlyInternetGateways",
  DESCRIBE_ELASTIC_GPUS: "DescribeElasticGpus",
  DESCRIBE_EXPORT_IMAGE_TASKS: "DescribeExportImageTasks",
  DESCRIBE_EXPORT_TASKS: "DescribeExportTasks",
  DESCRIBE_FAST_SNAPSHOT_RESTORES: "DescribeFastSnapshotRestores",
  DESCRIBE_FLEET_HISTORY: "DescribeFleetHistory",
  DESCRIBE_FLEET_INSTANCES: "DescribeFleetInstances",
  DESCRIBE_FLEETS: "DescribeFleets",
  DESCRIBE_FLOW_LOGS: "DescribeFlowLogs",
  DESCRIBE_FPGA_IMAGE_ATTRIBUTE: "DescribeFpgaImageAttribute",
  DESCRIBE_FPGA_IMAGES: "DescribeFpgaImages",
  DESCRIBE_HOST_RESERVATION_OFFERINGS: "DescribeHostReservationOfferings",
  DESCRIBE_HOST_RESERVATIONS: "DescribeHostReservations",
  DESCRIBE_HOSTS: "DescribeHosts",
  DESCRIBE_IAM_INSTANCE_PROFILE_ASSOCIATIONS:
    "DescribeIamInstanceProfileAssociations",
  DESCRIBE_IDENTITY_ID_FORMAT: "DescribeIdentityIdFormat",
  DESCRIBE_ID_FORMAT: "DescribeIdFormat",
  DESCRIBE_IMAGE_ATTRIBUTE: "DescribeImageAttribute",
  DESCRIBE_IMAGES: "DescribeImages",
  DESCRIBE_IMPORT_IMAGE_TASKS: "DescribeImportImageTasks",
  DESCRIBE_IMPORT_SNAPSHOT_TASKS: "DescribeImportSnapshotTasks",
  DESCRIBE_INSTANCE_ATTRIBUTE: "DescribeInstanceAttribute",
  DESCRIBE_INSTANCE_CREDIT_SPECIFICATIONS:
    "DescribeInstanceCreditSpecifications",
  DESCRIBE_INSTANCE_EVENT_NOTIFICATION_ATTRIBUTES:
    "DescribeInstanceEventNotificationAttributes",
  DESCRIBE_INSTANCES: "DescribeInstances",
  DESCRIBE_INSTANCE_STATUS: "DescribeInstanceStatus",
  DESCRIBE_INSTANCE_TYPE_OFFERINGS: "DescribeInstanceTypeOfferings",
  DESCRIBE_INSTANCE_TYPES: "DescribeInstanceTypes",
  DESCRIBE_INTERNET_GATEWAYS: "DescribeInternetGateways",
  DESCRIBE_IPV6_POOLS: "DescribeIpv6Pools",
  DESCRIBE_KEY_PAIRS: "DescribeKeyPairs",
  DESCRIBE_LAUNCH_TEMPLATES: "DescribeLaunchTemplates",
  DESCRIBE_LAUNCH_TEMPLATE_VERSIONS: "DescribeLaunchTemplateVersions",
  DESCRIBE_LOCAL_GATEWAY_ROUTE_TABLES: "DescribeLocalGatewayRouteTables",
  DESCRIBE_LOCAL_GATEWAY_ROUTE_TABLE_VIRTUAL_INTERFACE_GROUP_ASSOCIATIONS:
    "DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociations",
  DESCRIBE_LOCAL_GATEWAY_ROUTE_TABLE_VPC_ASSOCIATIONS:
    "DescribeLocalGatewayRouteTableVpcAssociations",
  DESCRIBE_LOCAL_GATEWAYS: "DescribeLocalGateways",
  DESCRIBE_LOCAL_GATEWAY_VIRTUAL_INTERFACE_GROUPS:
    "DescribeLocalGatewayVirtualInterfaceGroups",
  DESCRIBE_LOCAL_GATEWAY_VIRTUAL_INTERFACES:
    "DescribeLocalGatewayVirtualInterfaces",
  DESCRIBE_MANAGED_PREFIX_LISTS: "DescribeManagedPrefixLists",
  DESCRIBE_MOVING_ADDRESSES: "DescribeMovingAddresses",
  DESCRIBE_NAT_GATEWAYS: "DescribeNatGateways",
  DESCRIBE_NETWORK_ACLS: "DescribeNetworkAcls",
  DESCRIBE_NETWORK_INSIGHTS_ANALYSES: "DescribeNetworkInsightsAnalyses",
  DESCRIBE_NETWORK_INSIGHTS_PATHS: "DescribeNetworkInsightsPaths",
  DESCRIBE_NETWORK_INTERFACE_ATTRIBUTE: "DescribeNetworkInterfaceAttribute",
  DESCRIBE_NETWORK_INTERFACE_PERMISSIONS: "DescribeNetworkInterfacePermissions",
  DESCRIBE_NETWORK_INTERFACES: "DescribeNetworkInterfaces",
  DESCRIBE_PLACEMENT_GROUPS: "DescribePlacementGroups",
  DESCRIBE_PREFIX_LISTS: "DescribePrefixLists",
  DESCRIBE_PRINCIPAL_ID_FORMAT: "DescribePrincipalIdFormat",
  DESCRIBE_PUBLIC_IPV4_POOLS: "DescribePublicIpv4Pools",
  DESCRIBE_REGIONS: "DescribeRegions",
  DESCRIBE_RESERVED_INSTANCES: "DescribeReservedInstances",
  DESCRIBE_RESERVED_INSTANCES_LISTINGS: "DescribeReservedInstancesListings",
  DESCRIBE_RESERVED_INSTANCES_MODIFICATIONS:
    "DescribeReservedInstancesModifications",
  DESCRIBE_RESERVED_INSTANCES_OFFERINGS: "DescribeReservedInstancesOfferings",
  DESCRIBE_ROUTE_TABLES: "DescribeRouteTables",
  DESCRIBE_SCHEDULED_INSTANCE_AVAILABILITY:
    "DescribeScheduledInstanceAvailability",
  DESCRIBE_SCHEDULED_INSTANCES: "DescribeScheduledInstances",
  DESCRIBE_SECURITY_GROUP_REFERENCES: "DescribeSecurityGroupReferences",
  DESCRIBE_SECURITY_GROUPS: "DescribeSecurityGroups",
  DESCRIBE_SNAPSHOT_ATTRIBUTE: "DescribeSnapshotAttribute",
  DESCRIBE_SNAPSHOTS: "DescribeSnapshots",
  DESCRIBE_SPOT_DATAFEED_SUBSCRIPTION: "DescribeSpotDatafeedSubscription",
  DESCRIBE_SPOT_FLEET_INSTANCES: "DescribeSpotFleetInstances",
  DESCRIBE_SPOT_FLEET_REQUEST_HISTORY: "DescribeSpotFleetRequestHistory",
  DESCRIBE_SPOT_FLEET_REQUESTS: "DescribeSpotFleetRequests",
  DESCRIBE_SPOT_INSTANCE_REQUESTS: "DescribeSpotInstanceRequests",
  DESCRIBE_SPOT_PRICE_HISTORY: "DescribeSpotPriceHistory",
  DESCRIBE_STALE_SECURITY_GROUPS: "DescribeStaleSecurityGroups",
  DESCRIBE_SUBNETS: "DescribeSubnets",
  DESCRIBE_TAGS: "DescribeTags",
  DESCRIBE_TRAFFIC_MIRROR_FILTERS: "DescribeTrafficMirrorFilters",
  DESCRIBE_TRAFFIC_MIRROR_SESSIONS: "DescribeTrafficMirrorSessions",
  DESCRIBE_TRAFFIC_MIRROR_TARGETS: "DescribeTrafficMirrorTargets",
  DESCRIBE_TRANSIT_GATEWAY_ATTACHMENTS: "DescribeTransitGatewayAttachments",
  DESCRIBE_TRANSIT_GATEWAY_CONNECT_PEERS: "DescribeTransitGatewayConnectPeers",
  DESCRIBE_TRANSIT_GATEWAY_CONNECTS: "DescribeTransitGatewayConnects",
  DESCRIBE_TRANSIT_GATEWAY_MULTICAST_DOMAINS:
    "DescribeTransitGatewayMulticastDomains",
  DESCRIBE_TRANSIT_GATEWAY_PEERING_ATTACHMENTS:
    "DescribeTransitGatewayPeeringAttachments",
  DESCRIBE_TRANSIT_GATEWAY_ROUTE_TABLES: "DescribeTransitGatewayRouteTables",
  DESCRIBE_TRANSIT_GATEWAYS: "DescribeTransitGateways",
  DESCRIBE_TRANSIT_GATEWAY_VPC_ATTACHMENTS:
    "DescribeTransitGatewayVpcAttachments",
  DESCRIBE_VOLUME_ATTRIBUTE: "DescribeVolumeAttribute",
  DESCRIBE_VOLUMES: "DescribeVolumes",
  DESCRIBE_VOLUMES_MODIFICATIONS: "DescribeVolumesModifications",
  DESCRIBE_VOLUME_STATUS: "DescribeVolumeStatus",
  DESCRIBE_VPC_ATTRIBUTE: "DescribeVpcAttribute",
  DESCRIBE_VPC_CLASSIC_LINK: "DescribeVpcClassicLink",
  DESCRIBE_VPC_CLASSIC_LINK_DNS_SUPPORT: "DescribeVpcClassicLinkDnsSupport",
  DESCRIBE_VPC_ENDPOINT_CONNECTION_NOTIFICATIONS:
    "DescribeVpcEndpointConnectionNotifications",
  DESCRIBE_VPC_ENDPOINT_CONNECTIONS: "DescribeVpcEndpointConnections",
  DESCRIBE_VPC_ENDPOINTS: "DescribeVpcEndpoints",
  DESCRIBE_VPC_ENDPOINT_SERVICE_CONFIGURATIONS:
    "DescribeVpcEndpointServiceConfigurations",
  DESCRIBE_VPC_ENDPOINT_SERVICE_PERMISSIONS:
    "DescribeVpcEndpointServicePermissions",
  DESCRIBE_VPC_ENDPOINT_SERVICES: "DescribeVpcEndpointServices",
  DESCRIBE_VPC_PEERING_CONNECTIONS: "DescribeVpcPeeringConnections",
  DESCRIBE_VPCS: "DescribeVpcs",
  DESCRIBE_VPN_CONNECTIONS: "DescribeVpnConnections",
  DESCRIBE_VPN_GATEWAYS: "DescribeVpnGateways",
  DETACH_CLASSIC_LINK_VPC: "DetachClassicLinkVpc",
  DETACH_INTERNET_GATEWAY: "DetachInternetGateway",
  DETACH_NETWORK_INTERFACE: "DetachNetworkInterface",
  DETACH_VOLUME: "DetachVolume",
  DETACH_VPN_GATEWAY: "DetachVpnGateway",
  DISABLE_EBS_ENCRYPTION_BY_DEFAULT: "DisableEbsEncryptionByDefault",
  DISABLE_FAST_SNAPSHOT_RESTORES: "DisableFastSnapshotRestores",
  DISABLE_TRANSIT_GATEWAY_ROUTE_TABLE_PROPAGATION:
    "DisableTransitGatewayRouteTablePropagation",
  DISABLE_VGW_ROUTE_PROPAGATION: "DisableVgwRoutePropagation",
  DISABLE_VPC_CLASSIC_LINK: "DisableVpcClassicLink",
  DISABLE_VPC_CLASSIC_LINK_DNS_SUPPORT: "DisableVpcClassicLinkDnsSupport",
  DISASSOCIATE_ADDRESS: "DisassociateAddress",
  DISASSOCIATE_CLIENT_VPN_TARGET_NETWORK: "DisassociateClientVpnTargetNetwork",
  DISASSOCIATE_ENCLAVE_CERTIFICATE_IAM_ROLE:
    "DisassociateEnclaveCertificateIamRole",
  DISASSOCIATE_IAM_INSTANCE_PROFILE: "DisassociateIamInstanceProfile",
  DISASSOCIATE_ROUTE_TABLE: "DisassociateRouteTable",
  DISASSOCIATE_SUBNET_CIDR_BLOCK: "DisassociateSubnetCidrBlock",
  DISASSOCIATE_TRANSIT_GATEWAY_MULTICAST_DOMAIN:
    "DisassociateTransitGatewayMulticastDomain",
  DISASSOCIATE_TRANSIT_GATEWAY_ROUTE_TABLE:
    "DisassociateTransitGatewayRouteTable",
  DISASSOCIATE_VPC_CIDR_BLOCK: "DisassociateVpcCidrBlock",
  ENABLE_EBS_ENCRYPTION_BY_DEFAULT: "EnableEbsEncryptionByDefault",
  ENABLE_FAST_SNAPSHOT_RESTORES: "EnableFastSnapshotRestores",
  ENABLE_TRANSIT_GATEWAY_ROUTE_TABLE_PROPAGATION:
    "EnableTransitGatewayRouteTablePropagation",
  ENABLE_VGW_ROUTE_PROPAGATION: "EnableVgwRoutePropagation",
  ENABLE_VOLUME_IO: "EnableVolumeIO",
  ENABLE_VPC_CLASSIC_LINK: "EnableVpcClassicLink",
  ENABLE_VPC_CLASSIC_LINK_DNS_SUPPORT: "EnableVpcClassicLinkDnsSupport",
  EXPORT_CLIENT_VPN_CLIENT_CERTIFICATE_REVOCATION_LIST:
    "ExportClientVpnClientCertificateRevocationList",
  EXPORT_CLIENT_VPN_CLIENT_CONFIGURATION: "ExportClientVpnClientConfiguration",
  EXPORT_IMAGE: "ExportImage",
  EXPORT_TRANSIT_GATEWAY_ROUTES: "ExportTransitGatewayRoutes",
  GET_ASSOCIATED_ENCLAVE_CERTIFICATE_IAM_ROLES:
    "GetAssociatedEnclaveCertificateIamRoles",
  GET_ASSOCIATED_IPV6_POOL_CIDRS: "GetAssociatedIpv6PoolCidrs",
  GET_CAPACITY_RESERVATION_USAGE: "GetCapacityReservationUsage",
  GET_COIP_POOL_USAGE: "GetCoipPoolUsage",
  GET_CONSOLE_OUTPUT: "GetConsoleOutput",
  GET_CONSOLE_SCREENSHOT: "GetConsoleScreenshot",
  GET_DEFAULT_CREDIT_SPECIFICATION: "GetDefaultCreditSpecification",
  GET_EBS_DEFAULT_KMS_KEY_ID: "GetEbsDefaultKmsKeyId",
  GET_EBS_ENCRYPTION_BY_DEFAULT: "GetEbsEncryptionByDefault",
  GET_GROUPS_FOR_CAPACITY_RESERVATION: "GetGroupsForCapacityReservation",
  GET_HOST_RESERVATION_PURCHASE_PREVIEW: "GetHostReservationPurchasePreview",
  GET_LAUNCH_TEMPLATE_DATA: "GetLaunchTemplateData",
  GET_MANAGED_PREFIX_LIST_ASSOCIATIONS: "GetManagedPrefixListAssociations",
  GET_MANAGED_PREFIX_LIST_ENTRIES: "GetManagedPrefixListEntries",
  GET_PASSWORD_DATA: "GetPasswordData",
  GET_RESERVED_INSTANCES_EXCHANGE_QUOTE: "GetReservedInstancesExchangeQuote",
  GET_TRANSIT_GATEWAY_ATTACHMENT_PROPAGATIONS:
    "GetTransitGatewayAttachmentPropagations",
  GET_TRANSIT_GATEWAY_MULTICAST_DOMAIN_ASSOCIATIONS:
    "GetTransitGatewayMulticastDomainAssociations",
  GET_TRANSIT_GATEWAY_PREFIX_LIST_REFERENCES:
    "GetTransitGatewayPrefixListReferences",
  GET_TRANSIT_GATEWAY_ROUTE_TABLE_ASSOCIATIONS:
    "GetTransitGatewayRouteTableAssociations",
  GET_TRANSIT_GATEWAY_ROUTE_TABLE_PROPAGATIONS:
    "GetTransitGatewayRouteTablePropagations",
  IMPORT_CLIENT_VPN_CLIENT_CERTIFICATE_REVOCATION_LIST:
    "ImportClientVpnClientCertificateRevocationList",
  IMPORT_IMAGE: "ImportImage",
  IMPORT_INSTANCE: "ImportInstance",
  IMPORT_KEY_PAIR: "ImportKeyPair",
  IMPORT_SNAPSHOT: "ImportSnapshot",
  IMPORT_VOLUME: "ImportVolume",
  MODIFY_ADDRESS_ATTRIBUTE: "ModifyAddressAttribute",
  MODIFY_AVAILABILITY_ZONE_GROUP: "ModifyAvailabilityZoneGroup",
  MODIFY_CAPACITY_RESERVATION: "ModifyCapacityReservation",
  MODIFY_CLIENT_VPN_ENDPOINT: "ModifyClientVpnEndpoint",
  MODIFY_DEFAULT_CREDIT_SPECIFICATION: "ModifyDefaultCreditSpecification",
  MODIFY_EBS_DEFAULT_KMS_KEY_ID: "ModifyEbsDefaultKmsKeyId",
  MODIFY_FLEET: "ModifyFleet",
  MODIFY_FPGA_IMAGE_ATTRIBUTE: "ModifyFpgaImageAttribute",
  MODIFY_HOSTS: "ModifyHosts",
  MODIFY_IDENTITY_ID_FORMAT: "ModifyIdentityIdFormat",
  MODIFY_ID_FORMAT: "ModifyIdFormat",
  MODIFY_IMAGE_ATTRIBUTE: "ModifyImageAttribute",
  MODIFY_INSTANCE_ATTRIBUTE: "ModifyInstanceAttribute",
  MODIFY_INSTANCE_CAPACITY_RESERVATION_ATTRIBUTES:
    "ModifyInstanceCapacityReservationAttributes",
  MODIFY_INSTANCE_CREDIT_SPECIFICATION: "ModifyInstanceCreditSpecification",
  MODIFY_INSTANCE_EVENT_START_TIME: "ModifyInstanceEventStartTime",
  MODIFY_INSTANCE_METADATA_OPTIONS: "ModifyInstanceMetadataOptions",
  MODIFY_INSTANCE_PLACEMENT: "ModifyInstancePlacement",
  MODIFY_LAUNCH_TEMPLATE: "ModifyLaunchTemplate",
  MODIFY_MANAGED_PREFIX_LIST: "ModifyManagedPrefixList",
  MODIFY_NETWORK_INTERFACE_ATTRIBUTE: "ModifyNetworkInterfaceAttribute",
  MODIFY_RESERVED_INSTANCES: "ModifyReservedInstances",
  MODIFY_SNAPSHOT_ATTRIBUTE: "ModifySnapshotAttribute",
  MODIFY_SPOT_FLEET_REQUEST: "ModifySpotFleetRequest",
  MODIFY_SUBNET_ATTRIBUTE: "ModifySubnetAttribute",
  MODIFY_TRAFFIC_MIRROR_FILTER_NETWORK_SERVICES:
    "ModifyTrafficMirrorFilterNetworkServices",
  MODIFY_TRAFFIC_MIRROR_FILTER_RULE: "ModifyTrafficMirrorFilterRule",
  MODIFY_TRAFFIC_MIRROR_SESSION: "ModifyTrafficMirrorSession",
  MODIFY_TRANSIT_GATEWAY: "ModifyTransitGateway",
  MODIFY_TRANSIT_GATEWAY_PREFIX_LIST_REFERENCE:
    "ModifyTransitGatewayPrefixListReference",
  MODIFY_TRANSIT_GATEWAY_VPC_ATTACHMENT: "ModifyTransitGatewayVpcAttachment",
  MODIFY_VOLUME: "ModifyVolume",
  MODIFY_VOLUME_ATTRIBUTE: "ModifyVolumeAttribute",
  MODIFY_VPC_ATTRIBUTE: "ModifyVpcAttribute",
  MODIFY_VPC_ENDPOINT: "ModifyVpcEndpoint",
  MODIFY_VPC_ENDPOINT_CONNECTION_NOTIFICATION:
    "ModifyVpcEndpointConnectionNotification",
  MODIFY_VPC_ENDPOINT_SERVICE_CONFIGURATION:
    "ModifyVpcEndpointServiceConfiguration",
  MODIFY_VPC_ENDPOINT_SERVICE_PERMISSIONS:
    "ModifyVpcEndpointServicePermissions",
  MODIFY_VPC_PEERING_CONNECTION_OPTIONS: "ModifyVpcPeeringConnectionOptions",
  MODIFY_VPC_TENANCY: "ModifyVpcTenancy",
  MODIFY_VPN_CONNECTION: "ModifyVpnConnection",
  MODIFY_VPN_CONNECTION_OPTIONS: "ModifyVpnConnectionOptions",
  MODIFY_VPN_TUNNEL_CERTIFICATE: "ModifyVpnTunnelCertificate",
  MODIFY_VPN_TUNNEL_OPTIONS: "ModifyVpnTunnelOptions",
  MONITOR_INSTANCES: "MonitorInstances",
  MOVE_ADDRESS_TO_VPC: "MoveAddressToVpc",
  PROVISION_BYOIP_CIDR: "ProvisionByoipCidr",
  PURCHASE_HOST_RESERVATION: "PurchaseHostReservation",
  PURCHASE_RESERVED_INSTANCES_OFFERING: "PurchaseReservedInstancesOffering",
  PURCHASE_SCHEDULED_INSTANCES: "PurchaseScheduledInstances",
  REBOOT_INSTANCES: "RebootInstances",
  REGISTER_IMAGE: "RegisterImage",
  REGISTER_INSTANCE_EVENT_NOTIFICATION_ATTRIBUTES:
    "RegisterInstanceEventNotificationAttributes",
  REGISTER_TRANSIT_GATEWAY_MULTICAST_GROUP_MEMBERS:
    "RegisterTransitGatewayMulticastGroupMembers",
  REGISTER_TRANSIT_GATEWAY_MULTICAST_GROUP_SOURCES:
    "RegisterTransitGatewayMulticastGroupSources",
  REJECT_TRANSIT_GATEWAY_MULTICAST_DOMAIN_ASSOCIATIONS:
    "RejectTransitGatewayMulticastDomainAssociations",
  REJECT_TRANSIT_GATEWAY_PEERING_ATTACHMENT:
    "RejectTransitGatewayPeeringAttachment",
  REJECT_TRANSIT_GATEWAY_VPC_ATTACHMENT: "RejectTransitGatewayVpcAttachment",
  REJECT_VPC_ENDPOINT_CONNECTIONS: "RejectVpcEndpointConnections",
  REJECT_VPC_PEERING_CONNECTION: "RejectVpcPeeringConnection",
  RELEASE_ADDRESS: "ReleaseAddress",
  RELEASE_HOSTS: "ReleaseHosts",
  REPLACE_IAM_INSTANCE_PROFILE_ASSOCIATION:
    "ReplaceIamInstanceProfileAssociation",
  REPLACE_NETWORK_ACL_ASSOCIATION: "ReplaceNetworkAclAssociation",
  REPLACE_NETWORK_ACL_ENTRY: "ReplaceNetworkAclEntry",
  REPLACE_ROUTE: "ReplaceRoute",
  REPLACE_ROUTE_TABLE_ASSOCIATION: "ReplaceRouteTableAssociation",
  REPLACE_TRANSIT_GATEWAY_ROUTE: "ReplaceTransitGatewayRoute",
  REPORT_INSTANCE_STATUS: "ReportInstanceStatus",
  REQUEST_SPOT_FLEET: "RequestSpotFleet",
  REQUEST_SPOT_INSTANCES: "RequestSpotInstances",
  RESET_ADDRESS_ATTRIBUTE: "ResetAddressAttribute",
  RESET_EBS_DEFAULT_KMS_KEY_ID: "ResetEbsDefaultKmsKeyId",
  RESET_FPGA_IMAGE_ATTRIBUTE: "ResetFpgaImageAttribute",
  RESET_IMAGE_ATTRIBUTE: "ResetImageAttribute",
  RESET_INSTANCE_ATTRIBUTE: "ResetInstanceAttribute",
  RESET_NETWORK_INTERFACE_ATTRIBUTE: "ResetNetworkInterfaceAttribute",
  RESET_SNAPSHOT_ATTRIBUTE: "ResetSnapshotAttribute",
  RESTORE_ADDRESS_TO_CLASSIC: "RestoreAddressToClassic",
  RESTORE_MANAGED_PREFIX_LIST_VERSION: "RestoreManagedPrefixListVersion",
  REVOKE_CLIENT_VPN_INGRESS: "RevokeClientVpnIngress",
  REVOKE_SECURITY_GROUP_EGRESS: "RevokeSecurityGroupEgress",
  REVOKE_SECURITY_GROUP_INGRESS: "RevokeSecurityGroupIngress",
  RUN_INSTANCES: "RunInstances",
  RUN_SCHEDULED_INSTANCES: "RunScheduledInstances",
  SEARCH_LOCAL_GATEWAY_ROUTES: "SearchLocalGatewayRoutes",
  SEARCH_TRANSIT_GATEWAY_MULTICAST_GROUPS:
    "SearchTransitGatewayMulticastGroups",
  SEARCH_TRANSIT_GATEWAY_ROUTES: "SearchTransitGatewayRoutes",
  SEND_DIAGNOSTIC_INTERRUPT: "SendDiagnosticInterrupt",
  START_INSTANCES: "StartInstances",
  START_NETWORK_INSIGHTS_ANALYSIS: "StartNetworkInsightsAnalysis",
  START_VPC_ENDPOINT_SERVICE_PRIVATE_DNS_VERIFICATION:
    "StartVpcEndpointServicePrivateDnsVerification",
  STOP_INSTANCES: "StopInstances",
  TERMINATE_CLIENT_VPN_CONNECTIONS: "TerminateClientVpnConnections",
  TERMINATE_INSTANCES: "TerminateInstances",
  UNASSIGN_IPV6_ADDRESSES: "UnassignIpv6Addresses",
  UNASSIGN_PRIVATE_IP_ADDRESSES: "UnassignPrivateIpAddresses",
  UNMONITOR_INSTANCES: "UnmonitorInstances",
  UPDATE_SECURITY_GROUP_RULE_DESCRIPTIONS_EGRESS:
    "UpdateSecurityGroupRuleDescriptionsEgress",
  UPDATE_SECURITY_GROUP_RULE_DESCRIPTIONS_INGRESS:
    "UpdateSecurityGroupRuleDescriptionsIngress",
  WITHDRAW_BYOIP_CIDR: "WithdrawByoipCidr",
};
