// https://gist.github.com/shortjared/4c1e3fe52bdfa47522cfe5b41e5d6f22
export const AwsServicePrincipals = {
  A4B: "a4b.amazonaws.com",
  ACM_PCA: "acm-pca.amazonaws.com",
  ACM: "acm.amazonaws.com",
  ALEXA_APPKIT: "alexa-appkit.amazon.com",
  ALEXA_CONNECTED_HOME: "alexa-connectedhome.amazon.com",
  AMAZON_MQ: "amazonmq.amazonaws.com",
  APIGATEWAY: "apigateway.amazonaws.com",
  APPLICATION_AUTOSCALING: "application-autoscaling.amazonaws.com",
  APPSTREAM_APPLICATION_AUTOSCALING:
    "appstream.application-autoscaling.amazonaws.com",
  APPSYNC: "appsync.amazonaws.com",
  ATHENA: "athena.amazonaws.com",
  AUTOSCALING: "autoscaling.amazonaws.com",
  AWS_ARTIFACT_ACCOUNT_SYNC: "aws-artifact-account-sync.amazonaws.com",
  BACKUP: "backup.amazonaws.com",
  BATCH: "batch.amazonaws.com",
  BILLING_CONSOLE: "billingconsole.amazonaws.com",
  CE: "ce.amazonaws.com",
  CHANNELS_LEX: "channels.lex.amazonaws.com",
  CHIME: "chime.amazonaws.com",
  CLOUD9: "cloud9.amazonaws.com",
  CLOUDDIRECTORY: "clouddirectory.amazonaws.com",
  CLOUDFORMATION: "cloudformation.amazonaws.com",
  CLOUDFRONT: "cloudfront.amazonaws.com",
  CLOUDHSM: "cloudhsm.amazonaws.com",
  CLOUDSEARCH: "cloudsearch.amazonaws.com",
  CLOUDTRAIL: "cloudtrail.amazonaws.com",
  CLOUDWATCH_CROSS_ACCOUNT: "cloudwatch-crossaccount.amazonaws.com",
  CODEBUILD: "codebuild.amazonaws.com",
  CODECOMMIT: "codecommit.amazonaws.com",
  CODEDEPLOY: "codedeploy.amazonaws.com",
  CODEPIPELINE: "codepipeline.amazonaws.com",
  CODESTAR: "codestar.amazonaws.com",
  COGNITO_IDENTITY: "cognito-identity.amazonaws.com",
  COGNITO_IDP: "cognito-idp.amazonaws.com",
  COGNITO_SYNC: "cognito-sync.amazonaws.com",
  CONFIG_CONFORMS: "config-conforms.amazonaws.com",
  CONFIG_MULTIACCOUNT_SETUP: "config-multiaccountsetup.amazonaws.com",
  CONFIG: "config.amazonaws.com",
  CONNECT: "connect.amazonaws.com",
  CONTINUOUS_EXPORT: "continuousexport.discovery.amazonaws.com",
  CUSTOM_RESOURCE_APPLICATION_AUTOSCALING:
    "custom-resource.application-autoscaling.amazonaws.com",
  DATAPIPELINE: "datapipeline.amazonaws.com",
  DAX: "dax.amazonaws.com",
  DEEPLENS: "deeplens.amazonaws.com",
  DELIVERY_LOGS: "delivery.logs.amazonaws.com",
  DIODE: "diode.amazonaws.com",
  DIRECTCONNECT: "directconnect.amazonaws.com",
  DISCOVERY: "discovery.amazonaws.com",
  DLM: "dlm.amazonaws.com",
  DMS: "dms.amazonaws.com",
  DS: "ds.amazonaws.com",
  DYNAMODB: "dynamodb.amazonaws.com",
  DYNAMODB_APPLICATION_AUTOSCALING:
    "dynamodb.application-autoscaling.amazonaws.com",
  EC2: "ec2.amazonaws.com",
  EC2_APPLICATION_AUTOSCALING: "ec2.application-autoscaling.amazonaws.com",
  EC2_FLEET: "ec2fleet.amazonaws.com",
  EC2_SCHEDULED: "ec2scheduled.amazonaws.com",
  ECR: "ecr.amazonaws.com",
  ECS_TASKS: "ecs-tasks.amazonaws.com",
  ECS: "ecs.amazonaws.com",
  ECS_APPLICATION_AUTOSCALING: "ecs.application-autoscaling.amazonaws.com",
  EDGE_LAMBDA: "edgelambda.amazonaws.com",
  EKS: "eks.amazonaws.com",
  ELASTICACHE: "elasticache.amazonaws.com",
  ELASTIC_BEANSTALK: "elasticbeanstalk.amazonaws.com",
  ELASTIC_FILE_SYSTEM: "elasticfilesystem.amazonaws.com",
  ELASTIC_LOAD_BALANCING: "elasticloadbalancing.amazonaws.com",
  ELASTIC_MAPREDUCE: "elasticmapreduce.amazonaws.com",
  ELASTIC_TRANSCODER: "elastictranscoder.amazonaws.com",
  EMAIL_COGNITO_IDP: "email.cognito-idp.amazonaws.com",
  ES: "es.amazonaws.com",
  EVENTS: "events.amazonaws.com",
  FIREHOSE: "firehose.amazonaws.com",
  FMS: "fms.amazonaws.com",
  FREE_RTOS: "freertos.amazonaws.com",
  FSX: "fsx.amazonaws.com",
  GAMELIFT: "gamelift.amazonaws.com",
  GLACIER: "glacier.amazonaws.com",
  GLOBAL_ACCELERATOR: "globalaccelerator.amazonaws.com",
  GLUE: "glue.amazonaws.com",
  GREENGRASS: "greengrass.amazonaws.com",
  GUARDDUTY: "guardduty.amazonaws.com",
  HEALTH: "health.amazonaws.com",
  IAM: "iam.amazonaws.com",
  IMPORT_EXPORT: "importexport.amazonaws.com",
  INSPECTOR: "inspector.amazonaws.com",
  IOT: "iot.amazonaws.com",
  IOT_ANALYTICS: "iotanalytics.amazonaws.com",
  IOT_SITEWISE: "iotsitewise.amazonaws.com",
  IOT_THINGS_GRAPH: "iotthingsgraph.amazonaws.com",
  JELLYFISH: "jellyfish.amazonaws.com",
  KAFKA: "kafka.amazonaws.com",
  KINESIS: "kinesis.amazonaws.com",
  KINESIS_ANALYTICS: "kinesisanalytics.amazonaws.com",
  KMS: "kms.amazonaws.com",
  LAKEFORMATION: "lakeformation.amazonaws.com",
  LAMBDA: "lambda.amazonaws.com",
  LEX: "lex.amazonaws.com",
  LICENSE_MANAGER: "license-manager.amazonaws.com",
  LIGHTSAIL: "lightsail.amazonaws.com",
  LOGGER_CLOUDFRONT: "logger.cloudfront.amazonaws.com",
  LOGS: "logs.amazonaws.com",
  MACHINE_LEARNING: "machinelearning.amazonaws.com",
  MACIE: "macie.amazonaws.com",
  MANAGED_SERVICES: "managedservices.amazonaws.com",
  MEDIA_CONNECT: "mediaconnect.amazonaws.com",
  MEDIA_CONVERT: "mediaconvert.amazonaws.com",
  MEDIA_PACKAGE: "mediapackage.amazonaws.com",
  MEDIA_STORE: "mediastore.amazonaws.com",
  MEDIA_TAILOR: "mediatailor.amazonaws.com",
  METERING_MARKETPLACE: "metering-marketplace.amazonaws.com",
  MIGRATION_HUB: "migrationhub.amazonaws.com",
  MOBILEHUB: "mobilehub.amazonaws.com",
  MONITORING: "monitoring.amazonaws.com",
  MONITORING_RDS: "monitoring.rds.amazonaws.com",
  OPS_APIGATEWAY: "ops.apigateway.amazonaws.com",
  OPSWORKS_CM: "opsworks-cm.amazonaws.com",
  OPSWORKS: "opsworks.amazonaws.com",
  ORGANIZATIONS: "organizations.amazonaws.com",
  PINPOINT: "pinpoint.amazonaws.com",
  POLLY: "polly.amazonaws.com",
  QLDB: "qldb.amazonaws.com",
  QUICKSIGHT: "quicksight.amazonaws.com",
  RAM: "ram.amazonaws.com",
  RDS: "rds.amazonaws.com",
  REDSHIFT: "redshift.amazonaws.com",
  REKOGNITION: "rekognition.amazonaws.com",
  REPLICATION_DYNAMODB: "replication.dynamodb.amazonaws.com",
  REPLICATOR_LAMBDA: "replicator.lambda.amazonaws.com",
  RESOURCE_GROUPS: "resource-groups.amazonaws.com",
  ROBOMAKER: "robomaker.amazonaws.com",
  ROUTE53: "route53.amazonaws.com",
  ROUTE53_DOMAINS: "route53domains.amazonaws.com",
  ROUTE53_RESOLVER: "route53resolver.amazonaws.com",
  S3: "s3.amazonaws.com",
  SAGEMAKER: "sagemaker.amazonaws.com",
  SECRETS_MANAGER: "secretsmanager.amazonaws.com",
  SECURITY_HUB: "securityhub.amazonaws.com",
  SERVERLESS_REPO: "serverlessrepo.amazonaws.com",
  SERVICE_CATALOG: "servicecatalog.amazonaws.com",
  SERVICE_DISCOVERY: "servicediscovery.amazonaws.com",
  SES: "ses.amazonaws.com",
  SHIELD: "shield.amazonaws.com",
  SIGNER: "signer.amazonaws.com",
  SIGN_IN: "signin.amazonaws.com",
  SMS: "sms.amazonaws.com",
  SNS: "sns.amazonaws.com",
  SPOT_FLEET: "spotfleet.amazonaws.com",
  SQS: "sqs.amazonaws.com",
  SSM: "ssm.amazonaws.com",
  SSO: "sso.amazonaws.com",
  STATES: "states.amazonaws.com",
  STORAGE_GATEWAY: "storagegateway.amazonaws.com",
  STS: "sts.amazonaws.com",
  SUPPORT: "support.amazonaws.com",
  SWF: "swf.amazonaws.com",
  TAGGING: "tagging.amazonaws.com",
  TAG_POLICIES_TAG: "tagpolicies.tag.amazonaws.com",
  TRANSFER: "transfer.amazonaws.com",
  TRANSLATE: "translate.amazonaws.com",
  TRUSTED_ADVISOR: "trustedadvisor.amazonaws.com",
  TTS: "tts.amazonaws.com",
  VMIE: "vmie.amazonaws.com",
  WAF_REGIONAL: "waf-regional.amazonaws.com",
  WAF: "waf.amazonaws.com",
  WORKDOCS: "workdocs.amazonaws.com",
  WORKLINK: "worklink.amazonaws.com",
  WORKMAIL: "workmail.amazonaws.com",
  WORKSPACES: "workspaces.amazonaws.com",
  XRAY: "xray.amazonaws.com",
};

// https://gist.github.com/gene1wood/55b358748be3c314f956
export const AwsIamManagedPolicies = {
  API_GATEWAY_SERVICE_ROLE_POLICY: "APIGatewayServiceRolePolicy",
  AWS_ACCOUNT_ACTIVITY_ACCESS: "AWSAccountActivityAccess",
  AWS_ACCOUNT_USAGE_REPORT_ACCESS: "AWSAccountUsageReportAccess",
  AWS_AGENTLESS_DISCOVERY_SERVICE: "AWSAgentlessDiscoveryService",
  AWS_APP_MESH_ENVOY_ACCESS: "AWSAppMeshEnvoyAccess",
  AWS_APP_MESH_FULL_ACCESS: "AWSAppMeshFullAccess",
  AWS_APP_MESH_PREVIEW_ENVOY_ACCESS: "AWSAppMeshPreviewEnvoyAccess",
  AWS_APP_MESH_PREVIEW_SERVICE_ROLE_POLICY:
    "AWSAppMeshPreviewServiceRolePolicy",
  AWS_APP_MESH_READ_ONLY: "AWSAppMeshReadOnly",
  AWS_APP_MESH_SERVICE_ROLE_POLICY: "AWSAppMeshServiceRolePolicy",
  AWS_APP_SYNC_ADMINISTRATOR: "AWSAppSyncAdministrator",
  AWS_APP_SYNC_INVOKE_FULL_ACCESS: "AWSAppSyncInvokeFullAccess",
  AWS_APP_SYNC_PUSH_TO_CLOUD_WATCH_LOGS: "AWSAppSyncPushToCloudWatchLogs",
  AWS_APP_SYNC_SCHEMA_AUTHOR: "AWSAppSyncSchemaAuthor",
  AWS_APPLICATION_AUTO_SCALING_CUSTOM_RESOURCE_POLICY:
    "AWSApplicationAutoScalingCustomResourcePolicy",
  AWS_APPLICATION_AUTOSCALING_APP_STREAM_FLEET_POLICY:
    "AWSApplicationAutoscalingAppStreamFleetPolicy",
  AWS_APPLICATION_AUTOSCALING_COMPREHEND_ENDPOINT_POLICY:
    "AWSApplicationAutoscalingComprehendEndpointPolicy",
  AWS_APPLICATION_AUTOSCALING_DYNAMO_DB_TABLE_POLICY:
    "AWSApplicationAutoscalingDynamoDBTablePolicy",
  AWS_APPLICATION_AUTOSCALING_EC2_SPOT_FLEET_REQUEST_POLICY:
    "AWSApplicationAutoscalingEC2SpotFleetRequestPolicy",
  AWS_APPLICATION_AUTOSCALING_ECS_SERVICE_POLICY:
    "AWSApplicationAutoscalingECSServicePolicy",
  AWS_APPLICATION_AUTOSCALING_EMR_INSTANCE_GROUP_POLICY:
    "AWSApplicationAutoscalingEMRInstanceGroupPolicy",
  AWS_APPLICATION_AUTOSCALING_LAMBDA_CONCURRENCY_POLICY:
    "AWSApplicationAutoscalingLambdaConcurrencyPolicy",
  AWS_APPLICATION_AUTOSCALING_RDS_CLUSTER_POLICY:
    "AWSApplicationAutoscalingRDSClusterPolicy",
  AWS_APPLICATION_AUTOSCALING_SAGE_MAKER_ENDPOINT_POLICY:
    "AWSApplicationAutoscalingSageMakerEndpointPolicy",
  AWS_APPLICATION_DISCOVERY_AGENT_ACCESS: "AWSApplicationDiscoveryAgentAccess",
  AWS_APPLICATION_DISCOVERY_SERVICE_FULL_ACCESS:
    "AWSApplicationDiscoveryServiceFullAccess",
  AWS_ARTIFACT_ACCOUNT_SYNC: "AWSArtifactAccountSync",
  AWS_AUTO_SCALING_PLANS_EC2_AUTO_SCALING_POLICY:
    "AWSAutoScalingPlansEC2AutoScalingPolicy",
  AWS_B9_INTERNAL_SERVICE_POLICY: "AWSB9InternalServicePolicy",
  AWS_BACKUP_ADMIN_POLICY: "AWSBackupAdminPolicy",
  AWS_BACKUP_OPERATOR_POLICY: "AWSBackupOperatorPolicy",
  AWS_BACKUP_SERVICE_ROLE_POLICY_FOR_BACKUP:
    "AWSBackupServiceRolePolicyForBackup",
  AWS_BACKUP_SERVICE_ROLE_POLICY_FOR_RESTORES:
    "AWSBackupServiceRolePolicyForRestores",
  AWS_BATCH_FULL_ACCESS: "AWSBatchFullAccess",
  AWS_BATCH_SERVICE_EVENT_TARGET_ROLE: "AWSBatchServiceEventTargetRole",
  AWS_BATCH_SERVICE_ROLE: "AWSBatchServiceRole",
  AWS_CERTIFICATE_MANAGER_FULL_ACCESS: "AWSCertificateManagerFullAccess",
  AWS_CERTIFICATE_MANAGER_PRIVATE_CA_AUDITOR:
    "AWSCertificateManagerPrivateCAAuditor",
  AWS_CERTIFICATE_MANAGER_PRIVATE_CA_FULL_ACCESS:
    "AWSCertificateManagerPrivateCAFullAccess",
  AWS_CERTIFICATE_MANAGER_PRIVATE_CA_PRIVILEGED_USER:
    "AWSCertificateManagerPrivateCAPrivilegedUser",
  AWS_CERTIFICATE_MANAGER_PRIVATE_CA_READ_ONLY:
    "AWSCertificateManagerPrivateCAReadOnly",
  AWS_CERTIFICATE_MANAGER_PRIVATE_CA_USER: "AWSCertificateManagerPrivateCAUser",
  AWS_CERTIFICATE_MANAGER_READ_ONLY: "AWSCertificateManagerReadOnly",
  AWS_CHATBOT_SERVICE_LINKED_ROLE_POLICY: "AWSChatbotServiceLinkedRolePolicy",
  AWS_CLOUD9_ADMINISTRATOR: "AWSCloud9Administrator",
  AWS_CLOUD9_ENVIRONMENT_MEMBER: "AWSCloud9EnvironmentMember",
  AWS_CLOUD9_SERVICE_ROLE_POLICY: "AWSCloud9ServiceRolePolicy",
  AWS_CLOUD9_USER: "AWSCloud9User",
  AWS_CLOUD_FORMATION_FULL_ACCESS: "AWSCloudFormationFullAccess",
  AWS_CLOUD_FORMATION_READ_ONLY_ACCESS: "AWSCloudFormationReadOnlyAccess",
  AWS_CLOUD_FRONT_LOGGER: "AWSCloudFrontLogger",
  AWS_CLOUD_HSM_FULL_ACCESS: "AWSCloudHSMFullAccess",
  AWS_CLOUD_HSM_READ_ONLY_ACCESS: "AWSCloudHSMReadOnlyAccess",
  AWS_CLOUD_HSM_ROLE: "AWSCloudHSMRole",
  AWS_CLOUD_MAP_DISCOVER_INSTANCE_ACCESS: "AWSCloudMapDiscoverInstanceAccess",
  AWS_CLOUD_MAP_FULL_ACCESS: "AWSCloudMapFullAccess",
  AWS_CLOUD_MAP_READ_ONLY_ACCESS: "AWSCloudMapReadOnlyAccess",
  AWS_CLOUD_MAP_REGISTER_INSTANCE_ACCESS: "AWSCloudMapRegisterInstanceAccess",
  AWS_CLOUD_TRAIL_FULL_ACCESS: "AWSCloudTrailFullAccess",
  AWS_CLOUD_TRAIL_READ_ONLY_ACCESS: "AWSCloudTrailReadOnlyAccess",
  AWS_CODE_BUILD_ADMIN_ACCESS: "AWSCodeBuildAdminAccess",
  AWS_CODE_BUILD_DEVELOPER_ACCESS: "AWSCodeBuildDeveloperAccess",
  AWS_CODE_BUILD_READ_ONLY_ACCESS: "AWSCodeBuildReadOnlyAccess",
  AWS_CODE_COMMIT_FULL_ACCESS: "AWSCodeCommitFullAccess",
  AWS_CODE_COMMIT_POWER_USER: "AWSCodeCommitPowerUser",
  AWS_CODE_COMMIT_READ_ONLY: "AWSCodeCommitReadOnly",
  AWS_CODE_DEPLOY_DEPLOYER_ACCESS: "AWSCodeDeployDeployerAccess",
  AWS_CODE_DEPLOY_FULL_ACCESS: "AWSCodeDeployFullAccess",
  AWS_CODE_DEPLOY_READ_ONLY_ACCESS: "AWSCodeDeployReadOnlyAccess",
  AWS_CODE_DEPLOY_ROLE: "AWSCodeDeployRole",
  AWS_CODE_DEPLOY_ROLE_FOR_ECS: "AWSCodeDeployRoleForECS",
  AWS_CODE_DEPLOY_ROLE_FOR_ECS_LIMITED: "AWSCodeDeployRoleForECSLimited",
  AWS_CODE_DEPLOY_ROLE_FOR_LAMBDA: "AWSCodeDeployRoleForLambda",
  AWS_CODE_PIPELINE_APPROVER_ACCESS: "AWSCodePipelineApproverAccess",
  AWS_CODE_PIPELINE_CUSTOM_ACTION_ACCESS: "AWSCodePipelineCustomActionAccess",
  AWS_CODE_PIPELINE_FULL_ACCESS: "AWSCodePipelineFullAccess",
  AWS_CODE_PIPELINE_READ_ONLY_ACCESS: "AWSCodePipelineReadOnlyAccess",
  AWS_CODE_STAR_FULL_ACCESS: "AWSCodeStarFullAccess",
  AWS_CODE_STAR_NOTIFICATIONS_SERVICE_ROLE_POLICY:
    "AWSCodeStarNotificationsServiceRolePolicy",
  AWS_CODE_STAR_SERVICE_ROLE: "AWSCodeStarServiceRole",
  AWS_CONFIG_MULTI_ACCOUNT_SETUP_POLICY: "AWSConfigMultiAccountSetupPolicy",
  AWS_CONFIG_REMEDIATION_SERVICE_ROLE_POLICY:
    "AWSConfigRemediationServiceRolePolicy",
  AWS_CONFIG_ROLE: "AWSConfigRole",
  AWS_CONFIG_ROLE_FOR_ORGANIZATIONS: "AWSConfigRoleForOrganizations",
  AWS_CONFIG_RULES_EXECUTION_ROLE: "AWSConfigRulesExecutionRole",
  AWS_CONFIG_SERVICE_ROLE_POLICY: "AWSConfigServiceRolePolicy",
  AWS_CONFIG_USER_ACCESS: "AWSConfigUserAccess",
  AWS_CONNECTOR: "AWSConnector",
  AWS_CONTROL_TOWER_SERVICE_ROLE_POLICY: "AWSControlTowerServiceRolePolicy",
  AWS_DATA_EXCHANGE_FULL_ACCESS: "AWSDataExchangeFullAccess",
  AWS_DATA_EXCHANGE_PROVIDER_FULL_ACCESS: "AWSDataExchangeProviderFullAccess",
  AWS_DATA_EXCHANGE_READ_ONLY: "AWSDataExchangeReadOnly",
  AWS_DATA_EXCHANGE_SUBSCRIBER_FULL_ACCESS:
    "AWSDataExchangeSubscriberFullAccess",
  AWS_DATA_LIFECYCLE_MANAGER_SERVICE_ROLE: "AWSDataLifecycleManagerServiceRole",
  AWS_DATA_PIPELINE_ROLE: "AWSDataPipelineRole",
  AWS_DATA_PIPELINE_FULL_ACCESS: "AWSDataPipeline_FullAccess",
  AWS_DATA_PIPELINE_POWER_USER: "AWSDataPipeline_PowerUser",
  AWS_DATA_SYNC_FULL_ACCESS: "AWSDataSyncFullAccess",
  AWS_DATA_SYNC_READ_ONLY_ACCESS: "AWSDataSyncReadOnlyAccess",
  AWS_DEEP_LENS_LAMBDA_FUNCTION_ACCESS_POLICY:
    "AWSDeepLensLambdaFunctionAccessPolicy",
  AWS_DEEP_LENS_SERVICE_ROLE_POLICY: "AWSDeepLensServiceRolePolicy",
  AWS_DEEP_RACER_CLOUD_FORMATION_ACCESS_POLICY:
    "AWSDeepRacerCloudFormationAccessPolicy",
  AWS_DEEP_RACER_ROBO_MAKER_ACCESS_POLICY: "AWSDeepRacerRoboMakerAccessPolicy",
  AWS_DEEP_RACER_SERVICE_ROLE_POLICY: "AWSDeepRacerServiceRolePolicy",
  AWS_DENY_ALL: "AWSDenyAll",
  AWS_DEVICE_FARM_FULL_ACCESS: "AWSDeviceFarmFullAccess",
  AWS_DIRECT_CONNECT_FULL_ACCESS: "AWSDirectConnectFullAccess",
  AWS_DIRECT_CONNECT_READ_ONLY_ACCESS: "AWSDirectConnectReadOnlyAccess",
  AWS_DIRECTORY_SERVICE_FULL_ACCESS: "AWSDirectoryServiceFullAccess",
  AWS_DIRECTORY_SERVICE_READ_ONLY_ACCESS: "AWSDirectoryServiceReadOnlyAccess",
  AWS_DISCOVERY_CONTINUOUS_EXPORT_FIREHOSE_POLICY:
    "AWSDiscoveryContinuousExportFirehosePolicy",
  AWS_EC2_FLEET_SERVICE_ROLE_POLICY: "AWSEC2FleetServiceRolePolicy",
  AWS_EC2_SPOT_FLEET_SERVICE_ROLE_POLICY: "AWSEC2SpotFleetServiceRolePolicy",
  AWS_EC2_SPOT_SERVICE_ROLE_POLICY: "AWSEC2SpotServiceRolePolicy",
  AWS_ELASTIC_BEANSTALK_CUSTOM_PLATFORM_FOR_EC2_ROLE:
    "AWSElasticBeanstalkCustomPlatformforEC2Role",
  AWS_ELASTIC_BEANSTALK_ENHANCED_HEALTH: "AWSElasticBeanstalkEnhancedHealth",
  AWS_ELASTIC_BEANSTALK_FULL_ACCESS: "AWSElasticBeanstalkFullAccess",
  AWS_ELASTIC_BEANSTALK_MAINTENANCE: "AWSElasticBeanstalkMaintenance",
  AWS_ELASTIC_BEANSTALK_MULTICONTAINER_DOCKER:
    "AWSElasticBeanstalkMulticontainerDocker",
  AWS_ELASTIC_BEANSTALK_READ_ONLY_ACCESS: "AWSElasticBeanstalkReadOnlyAccess",
  AWS_ELASTIC_BEANSTALK_SERVICE: "AWSElasticBeanstalkService",
  AWS_ELASTIC_BEANSTALK_SERVICE_ROLE_POLICY:
    "AWSElasticBeanstalkServiceRolePolicy",
  AWS_ELASTIC_BEANSTALK_WEB_TIER: "AWSElasticBeanstalkWebTier",
  AWS_ELASTIC_BEANSTALK_WORKER_TIER: "AWSElasticBeanstalkWorkerTier",
  AWS_ELASTIC_LOAD_BALANCING_CLASSIC_SERVICE_ROLE_POLICY:
    "AWSElasticLoadBalancingClassicServiceRolePolicy",
  AWS_ELASTIC_LOAD_BALANCING_SERVICE_ROLE_POLICY:
    "AWSElasticLoadBalancingServiceRolePolicy",
  AWS_ELEMENTAL_MEDIA_CONVERT_FULL_ACCESS: "AWSElementalMediaConvertFullAccess",
  AWS_ELEMENTAL_MEDIA_CONVERT_READ_ONLY: "AWSElementalMediaConvertReadOnly",
  AWS_ELEMENTAL_MEDIA_PACKAGE_FULL_ACCESS: "AWSElementalMediaPackageFullAccess",
  AWS_ELEMENTAL_MEDIA_PACKAGE_READ_ONLY: "AWSElementalMediaPackageReadOnly",
  AWS_ELEMENTAL_MEDIA_STORE_FULL_ACCESS: "AWSElementalMediaStoreFullAccess",
  AWS_ELEMENTAL_MEDIA_STORE_READ_ONLY: "AWSElementalMediaStoreReadOnly",
  AWS_ENHANCED_CLASSIC_NETWORKING_MANGEMENT_POLICY:
    "AWSEnhancedClassicNetworkingMangementPolicy",
  AWS_FM_ADMIN_FULL_ACCESS: "AWSFMAdminFullAccess",
  AWS_FM_ADMIN_READ_ONLY_ACCESS: "AWSFMAdminReadOnlyAccess",
  AWS_FM_MEMBER_READ_ONLY_ACCESS: "AWSFMMemberReadOnlyAccess",
  AWS_FOR_WORD_PRESS_PLUGIN_POLICY: "AWSForWordPressPluginPolicy",
  AWS_GLOBAL_ACCELERATOR_SLR_POLICY: "AWSGlobalAcceleratorSLRPolicy",
  AWS_GLUE_CONSOLE_FULL_ACCESS: "AWSGlueConsoleFullAccess",
  AWS_GLUE_CONSOLE_SAGE_MAKER_NOTEBOOK_FULL_ACCESS:
    "AWSGlueConsoleSageMakerNotebookFullAccess",
  AWS_GLUE_SERVICE_NOTEBOOK_ROLE: "AWSGlueServiceNotebookRole",
  AWS_GLUE_SERVICE_ROLE: "AWSGlueServiceRole",
  AWS_GREENGRASS_FULL_ACCESS: "AWSGreengrassFullAccess",
  AWS_GREENGRASS_READ_ONLY_ACCESS: "AWSGreengrassReadOnlyAccess",
  AWS_GREENGRASS_RESOURCE_ACCESS_ROLE_POLICY:
    "AWSGreengrassResourceAccessRolePolicy",
  AWS_HEALTH_FULL_ACCESS: "AWSHealthFullAccess",
  AWS_IQ_CONTRACT_SERVICE_ROLE_POLICY: "AWSIQContractServiceRolePolicy",
  AWS_IQ_FULL_ACCESS: "AWSIQFullAccess",
  AWS_IQ_PERMISSION_SERVICE_ROLE_POLICY: "AWSIQPermissionServiceRolePolicy",
  AWS_IMPORT_EXPORT_FULL_ACCESS: "AWSImportExportFullAccess",
  AWS_IMPORT_EXPORT_READ_ONLY_ACCESS: "AWSImportExportReadOnlyAccess",
  AWS_IOT1_CLICK_FULL_ACCESS: "AWSIoT1ClickFullAccess",
  AWS_IOT1_CLICK_READ_ONLY_ACCESS: "AWSIoT1ClickReadOnlyAccess",
  AWS_IOT_ANALYTICS_FULL_ACCESS: "AWSIoTAnalyticsFullAccess",
  AWS_IOT_ANALYTICS_READ_ONLY_ACCESS: "AWSIoTAnalyticsReadOnlyAccess",
  AWS_IOT_CONFIG_ACCESS: "AWSIoTConfigAccess",
  AWS_IOT_CONFIG_READ_ONLY_ACCESS: "AWSIoTConfigReadOnlyAccess",
  AWS_IOT_DATA_ACCESS: "AWSIoTDataAccess",
  AWS_IOT_DEVICE_DEFENDER_ADD_THINGS_TO_THING_GROUP_MITIGATION_ACTION:
    "AWSIoTDeviceDefenderAddThingsToThingGroupMitigationAction",
  AWS_IOT_DEVICE_DEFENDER_AUDIT: "AWSIoTDeviceDefenderAudit",
  AWS_IOT_DEVICE_DEFENDER_ENABLE_IOT_LOGGING_MITIGATION_ACTION:
    "AWSIoTDeviceDefenderEnableIoTLoggingMitigationAction",
  AWS_IOT_DEVICE_DEFENDER_PUBLISH_FINDINGS_TO_SNS_MITIGATION_ACTION:
    "AWSIoTDeviceDefenderPublishFindingsToSNSMitigationAction",
  AWS_IOT_DEVICE_DEFENDER_REPLACE_DEFAULT_POLICY_MITIGATION_ACTION:
    "AWSIoTDeviceDefenderReplaceDefaultPolicyMitigationAction",
  AWS_IOT_DEVICE_DEFENDER_UPDATE_CA_CERT_MITIGATION_ACTION:
    "AWSIoTDeviceDefenderUpdateCACertMitigationAction",
  AWS_IOT_DEVICE_DEFENDER_UPDATE_DEVICE_CERT_MITIGATION_ACTION:
    "AWSIoTDeviceDefenderUpdateDeviceCertMitigationAction",
  AWS_IOT_EVENTS_FULL_ACCESS: "AWSIoTEventsFullAccess",
  AWS_IOT_EVENTS_READ_ONLY_ACCESS: "AWSIoTEventsReadOnlyAccess",
  AWS_IOT_FULL_ACCESS: "AWSIoTFullAccess",
  AWS_IOT_LOGGING: "AWSIoTLogging",
  AWS_IOT_OTA_UPDATE: "AWSIoTOTAUpdate",
  AWS_IOT_RULE_ACTIONS: "AWSIoTRuleActions",
  AWS_IOT_SITE_WISE_CONSOLE_FULL_ACCESS: "AWSIoTSiteWiseConsoleFullAccess",
  AWS_IOT_SITE_WISE_FULL_ACCESS: "AWSIoTSiteWiseFullAccess",
  AWS_IOT_SITE_WISE_MONITOR_SERVICE_ROLE_POLICY:
    "AWSIoTSiteWiseMonitorServiceRolePolicy",
  AWS_IOT_SITE_WISE_READ_ONLY_ACCESS: "AWSIoTSiteWiseReadOnlyAccess",
  AWS_IOT_THINGS_REGISTRATION: "AWSIoTThingsRegistration",
  AWS_KEY_MANAGEMENT_SERVICE_CUSTOM_KEY_STORES_SERVICE_ROLE_POLICY:
    "AWSKeyManagementServiceCustomKeyStoresServiceRolePolicy",
  AWS_KEY_MANAGEMENT_SERVICE_POWER_USER: "AWSKeyManagementServicePowerUser",
  AWS_LAKE_FORMATION_DATA_ADMIN: "AWSLakeFormationDataAdmin",
  AWS_LAMBDA_BASIC_EXECUTION_ROLE: "AWSLambdaBasicExecutionRole",
  AWS_LAMBDA_DYNAMO_DB_EXECUTION_ROLE: "AWSLambdaDynamoDBExecutionRole",
  AWS_LAMBDA_ENI_MANAGEMENT_ACCESS: "AWSLambdaENIManagementAccess",
  AWS_LAMBDA_EXECUTE: "AWSLambdaExecute",
  AWS_LAMBDA_FULL_ACCESS: "AWSLambdaFullAccess",
  AWS_LAMBDA_INVOCATION_DYNAMO_DB: "AWSLambdaInvocation-DynamoDB",
  AWS_LAMBDA_KINESIS_EXECUTION_ROLE: "AWSLambdaKinesisExecutionRole",
  AWS_LAMBDA_READ_ONLY_ACCESS: "AWSLambdaReadOnlyAccess",
  AWS_LAMBDA_REPLICATOR: "AWSLambdaReplicator",
  AWS_LAMBDA_ROLE: "AWSLambdaRole",
  AWS_LAMBDA_SQS_QUEUE_EXECUTION_ROLE: "AWSLambdaSQSQueueExecutionRole",
  AWS_LAMBDA_VPC_ACCESS_EXECUTION_ROLE: "AWSLambdaVPCAccessExecutionRole",
  AWS_LICENSE_MANAGER_MASTER_ACCOUNT_ROLE_POLICY:
    "AWSLicenseManagerMasterAccountRolePolicy",
  AWS_LICENSE_MANAGER_MEMBER_ACCOUNT_ROLE_POLICY:
    "AWSLicenseManagerMemberAccountRolePolicy",
  AWS_LICENSE_MANAGER_SERVICE_ROLE_POLICY: "AWSLicenseManagerServiceRolePolicy",
  AWS_MARKETPLACE_FULL_ACCESS: "AWSMarketplaceFullAccess",
  AWS_MARKETPLACE_GET_ENTITLEMENTS: "AWSMarketplaceGetEntitlements",
  AWS_MARKETPLACE_IMAGE_BUILD_FULL_ACCESS: "AWSMarketplaceImageBuildFullAccess",
  AWS_MARKETPLACE_MANAGE_SUBSCRIPTIONS: "AWSMarketplaceManageSubscriptions",
  AWS_MARKETPLACE_METERING_FULL_ACCESS: "AWSMarketplaceMeteringFullAccess",
  AWS_MARKETPLACE_PROCUREMENT_SYSTEM_ADMIN_FULL_ACCESS:
    "AWSMarketplaceProcurementSystemAdminFullAccess",
  AWS_MARKETPLACE_READ_ONLY: "AWSMarketplaceRead-only",
  AWS_MARKETPLACE_SELLER_FULL_ACCESS: "AWSMarketplaceSellerFullAccess",
  AWS_MARKETPLACE_SELLER_PRODUCTS_FULL_ACCESS:
    "AWSMarketplaceSellerProductsFullAccess",
  AWS_MARKETPLACE_SELLER_PRODUCTS_READ_ONLY:
    "AWSMarketplaceSellerProductsReadOnly",
  AWS_MIGRATION_HUB_DMS_ACCESS: "AWSMigrationHubDMSAccess",
  AWS_MIGRATION_HUB_DISCOVERY_ACCESS: "AWSMigrationHubDiscoveryAccess",
  AWS_MIGRATION_HUB_FULL_ACCESS: "AWSMigrationHubFullAccess",
  AWS_MIGRATION_HUB_SMS_ACCESS: "AWSMigrationHubSMSAccess",
  AWS_MOBILE_HUB_FULL_ACCESS: "AWSMobileHub_FullAccess",
  AWS_MOBILE_HUB_READ_ONLY: "AWSMobileHub_ReadOnly",
  AWS_OPS_WORKS_CM_INSTANCE_PROFILE_ROLE: "AWSOpsWorksCMInstanceProfileRole",
  AWS_OPS_WORKS_CM_SERVICE_ROLE: "AWSOpsWorksCMServiceRole",
  AWS_OPS_WORKS_CLOUD_WATCH_LOGS: "AWSOpsWorksCloudWatchLogs",
  AWS_OPS_WORKS_FULL_ACCESS: "AWSOpsWorksFullAccess",
  AWS_OPS_WORKS_INSTANCE_REGISTRATION: "AWSOpsWorksInstanceRegistration",
  AWS_OPS_WORKS_REGISTER_CLI_EC2: "AWSOpsWorksRegisterCLI_EC2",
  AWS_OPS_WORKS_REGISTER_CLI_ON_PREMISES: "AWSOpsWorksRegisterCLI_OnPremises",
  AWS_OPS_WORKS_ROLE: "AWSOpsWorksRole",
  AWS_ORGANIZATIONS_FULL_ACCESS: "AWSOrganizationsFullAccess",
  AWS_ORGANIZATIONS_READ_ONLY_ACCESS: "AWSOrganizationsReadOnlyAccess",
  AWS_ORGANIZATIONS_SERVICE_TRUST_POLICY: "AWSOrganizationsServiceTrustPolicy",
  AWS_PRICE_LIST_SERVICE_FULL_ACCESS: "AWSPriceListServiceFullAccess",
  AWS_PRIVATE_MARKETPLACE_ADMIN_FULL_ACCESS:
    "AWSPrivateMarketplaceAdminFullAccess",
  AWS_PRIVATE_MARKETPLACE_REQUESTS: "AWSPrivateMarketplaceRequests",
  AWS_QUICK_SIGHT_DESCRIBE_RDS: "AWSQuickSightDescribeRDS",
  AWS_QUICK_SIGHT_DESCRIBE_REDSHIFT: "AWSQuickSightDescribeRedshift",
  AWS_QUICK_SIGHT_IOT_ANALYTICS_ACCESS: "AWSQuickSightIoTAnalyticsAccess",
  AWS_QUICK_SIGHT_LIST_IAM: "AWSQuickSightListIAM",
  AWS_QUICKSIGHT_ATHENA_ACCESS: "AWSQuicksightAthenaAccess",
  AWS_RESOURCE_ACCESS_MANAGER_FULL_ACCESS: "AWSResourceAccessManagerFullAccess",
  AWS_RESOURCE_ACCESS_MANAGER_SERVICE_ROLE_POLICY:
    "AWSResourceAccessManagerServiceRolePolicy",
  AWS_RESOURCE_GROUPS_READ_ONLY_ACCESS: "AWSResourceGroupsReadOnlyAccess",
  AWS_ROBO_MAKER_FULL_ACCESS: "AWSRoboMakerFullAccess",
  AWS_ROBO_MAKER_READ_ONLY_ACCESS: "AWSRoboMakerReadOnlyAccess",
  AWS_ROBO_MAKER_SERVICE_POLICY: "AWSRoboMakerServicePolicy",
  AWS_ROBO_MAKER_SERVICE_ROLE_POLICY: "AWSRoboMakerServiceRolePolicy",
  AWS_SSO_DIRECTORY_ADMINISTRATOR: "AWSSSODirectoryAdministrator",
  AWS_SSO_DIRECTORY_READ_ONLY: "AWSSSODirectoryReadOnly",
  AWS_SSO_MASTER_ACCOUNT_ADMINISTRATOR: "AWSSSOMasterAccountAdministrator",
  AWS_SSO_MEMBER_ACCOUNT_ADMINISTRATOR: "AWSSSOMemberAccountAdministrator",
  AWS_SSO_READ_ONLY: "AWSSSOReadOnly",
  AWS_SSO_SERVICE_ROLE_POLICY: "AWSSSOServiceRolePolicy",
  AWS_SAVINGS_PLANS_FULL_ACCESS: "AWSSavingsPlansFullAccess",
  AWS_SAVINGS_PLANS_READ_ONLY_ACCESS: "AWSSavingsPlansReadOnlyAccess",
  AWS_SCHEMAS_SERVICE_ROLE_POLICY: "AWSSchemasServiceRolePolicy",
  AWS_SECURITY_HUB_FULL_ACCESS: "AWSSecurityHubFullAccess",
  AWS_SECURITY_HUB_READ_ONLY_ACCESS: "AWSSecurityHubReadOnlyAccess",
  AWS_SECURITY_HUB_SERVICE_ROLE_POLICY: "AWSSecurityHubServiceRolePolicy",
  AWS_SERVICE_CATALOG_ADMIN_FULL_ACCESS: "AWSServiceCatalogAdminFullAccess",
  AWS_SERVICE_CATALOG_ADMIN_READ_ONLY_ACCESS:
    "AWSServiceCatalogAdminReadOnlyAccess",
  AWS_SERVICE_CATALOG_END_USER_FULL_ACCESS:
    "AWSServiceCatalogEndUserFullAccess",
  AWS_SERVICE_CATALOG_END_USER_READ_ONLY_ACCESS:
    "AWSServiceCatalogEndUserReadOnlyAccess",
  AWS_SERVICE_ROLE_FOR_AMAZON_EKS_NODEGROUP:
    "AWSServiceRoleForAmazonEKSNodegroup",
  AWS_SERVICE_ROLE_FOR_EC2_SCHEDULED_INSTANCES:
    "AWSServiceRoleForEC2ScheduledInstances",
  AWS_SERVICE_ROLE_FOR_IOT_SITE_WISE: "AWSServiceRoleForIoTSiteWise",
  AWS_SERVICE_ROLE_FOR_LOG_DELIVERY_POLICY:
    "AWSServiceRoleForLogDeliveryPolicy",
  AWS_SERVICE_ROLE_FOR_SMS: "AWSServiceRoleForSMS",
  AWS_SHIELD_DRT_ACCESS_POLICY: "AWSShieldDRTAccessPolicy",
  AWS_STEP_FUNCTIONS_CONSOLE_FULL_ACCESS: "AWSStepFunctionsConsoleFullAccess",
  AWS_STEP_FUNCTIONS_FULL_ACCESS: "AWSStepFunctionsFullAccess",
  AWS_STEP_FUNCTIONS_READ_ONLY_ACCESS: "AWSStepFunctionsReadOnlyAccess",
  AWS_STORAGE_GATEWAY_FULL_ACCESS: "AWSStorageGatewayFullAccess",
  AWS_STORAGE_GATEWAY_READ_ONLY_ACCESS: "AWSStorageGatewayReadOnlyAccess",
  AWS_SUPPORT_ACCESS: "AWSSupportAccess",
  AWS_SUPPORT_SERVICE_ROLE_POLICY: "AWSSupportServiceRolePolicy",
  AWS_SYSTEMS_MANAGER_ACCOUNT_DISCOVERY_SERVICE_POLICY:
    "AWSSystemsManagerAccountDiscoveryServicePolicy",
  AWS_TRANSFER_LOGGING_ACCESS: "AWSTransferLoggingAccess",
  AWS_TRUSTED_ADVISOR_SERVICE_ROLE_POLICY: "AWSTrustedAdvisorServiceRolePolicy",
  AWS_VPC_S2_S_VPN_SERVICE_ROLE_POLICY: "AWSVPCS2SVpnServiceRolePolicy",
  AWS_VPC_TRANSIT_GATEWAY_SERVICE_ROLE_POLICY:
    "AWSVPCTransitGatewayServiceRolePolicy",
  AWS_WAF_FULL_ACCESS: "AWSWAFFullAccess",
  AWS_WAF_READ_ONLY_ACCESS: "AWSWAFReadOnlyAccess",
  AWS_X_RAY_DAEMON_WRITE_ACCESS: "AWSXRayDaemonWriteAccess",
  AWS_XRAY_FULL_ACCESS: "AWSXrayFullAccess",
  AWS_XRAY_READ_ONLY_ACCESS: "AWSXrayReadOnlyAccess",
  AWS_XRAY_WRITE_ONLY_ACCESS: "AWSXrayWriteOnlyAccess",
  ADMINISTRATOR_ACCESS: "AdministratorAccess",
  ALEXA_FOR_BUSINESS_DEVICE_SETUP: "AlexaForBusinessDeviceSetup",
  ALEXA_FOR_BUSINESS_FULL_ACCESS: "AlexaForBusinessFullAccess",
  ALEXA_FOR_BUSINESS_GATEWAY_EXECUTION: "AlexaForBusinessGatewayExecution",
  ALEXA_FOR_BUSINESS_NETWORK_PROFILE_SERVICE_POLICY:
    "AlexaForBusinessNetworkProfileServicePolicy",
  ALEXA_FOR_BUSINESS_POLY_DELEGATED_ACCESS_POLICY:
    "AlexaForBusinessPolyDelegatedAccessPolicy",
  ALEXA_FOR_BUSINESS_READ_ONLY_ACCESS: "AlexaForBusinessReadOnlyAccess",
  AMAZON_API_GATEWAY_ADMINISTRATOR: "AmazonAPIGatewayAdministrator",
  AMAZON_API_GATEWAY_INVOKE_FULL_ACCESS: "AmazonAPIGatewayInvokeFullAccess",
  AMAZON_API_GATEWAY_PUSH_TO_CLOUD_WATCH_LOGS:
    "AmazonAPIGatewayPushToCloudWatchLogs",
  AMAZON_APP_STREAM_FULL_ACCESS: "AmazonAppStreamFullAccess",
  AMAZON_APP_STREAM_READ_ONLY_ACCESS: "AmazonAppStreamReadOnlyAccess",
  AMAZON_APP_STREAM_SERVICE_ACCESS: "AmazonAppStreamServiceAccess",
  AMAZON_ATHENA_FULL_ACCESS: "AmazonAthenaFullAccess",
  AMAZON_CHIME_FULL_ACCESS: "AmazonChimeFullAccess",
  AMAZON_CHIME_READ_ONLY: "AmazonChimeReadOnly",
  AMAZON_CHIME_SERVICE_ROLE_POLICY: "AmazonChimeServiceRolePolicy",
  AMAZON_CHIME_USER_MANAGEMENT: "AmazonChimeUserManagement",
  AMAZON_CHIME_VOICE_CONNECTOR_SERVICE_LINKED_ROLE_POLICY:
    "AmazonChimeVoiceConnectorServiceLinkedRolePolicy",
  AMAZON_CLOUD_DIRECTORY_FULL_ACCESS: "AmazonCloudDirectoryFullAccess",
  AMAZON_CLOUD_DIRECTORY_READ_ONLY_ACCESS: "AmazonCloudDirectoryReadOnlyAccess",
  AMAZON_COGNITO_DEVELOPER_AUTHENTICATED_IDENTITIES:
    "AmazonCognitoDeveloperAuthenticatedIdentities",
  AMAZON_COGNITO_IDP_EMAIL_SERVICE_ROLE_POLICY:
    "AmazonCognitoIdpEmailServiceRolePolicy",
  AMAZON_COGNITO_POWER_USER: "AmazonCognitoPowerUser",
  AMAZON_COGNITO_READ_ONLY: "AmazonCognitoReadOnly",
  AMAZON_CONNECT_FULL_ACCESS: "AmazonConnectFullAccess",
  AMAZON_CONNECT_READ_ONLY_ACCESS: "AmazonConnectReadOnlyAccess",
  AMAZON_CONNECT_SERVICE_LINKED_ROLE_POLICY:
    "AmazonConnectServiceLinkedRolePolicy",
  AMAZON_DMS_CLOUD_WATCH_LOGS_ROLE: "AmazonDMSCloudWatchLogsRole",
  AMAZON_DMS_REDSHIFT_S3_ROLE: "AmazonDMSRedshiftS3Role",
  AMAZON_DMS_VPC_MANAGEMENT_ROLE: "AmazonDMSVPCManagementRole",
  AMAZON_DRS_VPC_MANAGEMENT: "AmazonDRSVPCManagement",
  AMAZON_DOC_DB_CONSOLE_FULL_ACCESS: "AmazonDocDBConsoleFullAccess",
  AMAZON_DOC_DB_FULL_ACCESS: "AmazonDocDBFullAccess",
  AMAZON_DOC_DB_READ_ONLY_ACCESS: "AmazonDocDBReadOnlyAccess",
  AMAZON_DYNAMO_DB_FULL_ACCESS: "AmazonDynamoDBFullAccess",
  AMAZON_DYNAMO_DB_FULL_ACCESS_WITH_DATA_PIPELINE:
    "AmazonDynamoDBFullAccesswithDataPipeline",
  AMAZON_DYNAMO_DB_READ_ONLY_ACCESS: "AmazonDynamoDBReadOnlyAccess",
  AMAZON_EC2_CONTAINER_REGISTRY_FULL_ACCESS:
    "AmazonEC2ContainerRegistryFullAccess",
  AMAZON_EC2_CONTAINER_REGISTRY_POWER_USER:
    "AmazonEC2ContainerRegistryPowerUser",
  AMAZON_EC2_CONTAINER_REGISTRY_READ_ONLY: "AmazonEC2ContainerRegistryReadOnly",
  AMAZON_EC2_CONTAINER_SERVICE_AUTO_SCALE_ROLE:
    "AmazonEC2ContainerServiceAutoscaleRole",
  AMAZON_EC2_CONTAINER_SERVICE_EVENTS_ROLE:
    "AmazonEC2ContainerServiceEventsRole",
  AMAZON_EC2_CONTAINER_SERVICE_FULL_ACCESS:
    "AmazonEC2ContainerServiceFullAccess",
  AMAZON_EC2_CONTAINER_SERVICE_ROLE: "AmazonEC2ContainerServiceRole",
  AMAZON_EC2_CONTAINER_SERVICE_FOR_EC2_ROLE:
    "AmazonEC2ContainerServiceforEC2Role",
  AMAZON_EC2_FULL_ACCESS: "AmazonEC2FullAccess",
  AMAZON_EC2_READ_ONLY_ACCESS: "AmazonEC2ReadOnlyAccess",
  AMAZON_EC2_REPORTS_ACCESS: "AmazonEC2ReportsAccess",
  AMAZON_EC2_ROLE_POLICY_FOR_LAUNCH_WIZARD:
    "AmazonEC2RolePolicyForLaunchWizard",
  AMAZON_EC2_ROLE_FOR_AWS_CODE_DEPLOY: "AmazonEC2RoleforAWSCodeDeploy",
  AMAZON_EC2_ROLE_FOR_DATA_PIPELINE_ROLE: "AmazonEC2RoleforDataPipelineRole",
  AMAZON_EC2_ROLE_FOR_SSM: "AmazonEC2RoleforSSM",
  AMAZON_EC2_SPOT_FLEET_AUTO_SCALE_ROLE: "AmazonEC2SpotFleetAutoscaleRole",
  AMAZON_EC2_SPOT_FLEET_TAGGING_ROLE: "AmazonEC2SpotFleetTaggingRole",
  AMAZON_ECS_SERVICE_ROLE_POLICY: "AmazonECSServiceRolePolicy",
  AMAZON_ECS_TASK_EXECUTION_ROLE_POLICY: "AmazonECSTaskExecutionRolePolicy",
  AMAZON_ECS_FULL_ACCESS: "AmazonECS_FullAccess",
  AMAZON_EKS_CLUSTER_POLICY: "AmazonEKSClusterPolicy",
  AMAZON_EKS_SERVICE_POLICY: "AmazonEKSServicePolicy",
  AMAZON_EKS_WORKER_NODE_POLICY: "AmazonEKSWorkerNodePolicy",
  AMAZON_EKS_CNI_POLICY: "AmazonEKS_CNI_Policy",
  AMAZON_EMR_CLEANUP_POLICY: "AmazonEMRCleanupPolicy",
  AMAZON_ES_COGNITO_ACCESS: "AmazonESCognitoAccess",
  AMAZON_ES_FULL_ACCESS: "AmazonESFullAccess",
  AMAZON_ES_READ_ONLY_ACCESS: "AmazonESReadOnlyAccess",
  AMAZON_ELASTI_CACHE_FULL_ACCESS: "AmazonElastiCacheFullAccess",
  AMAZON_ELASTI_CACHE_READ_ONLY_ACCESS: "AmazonElastiCacheReadOnlyAccess",
  AMAZON_ELASTIC_FILE_SYSTEM_FULL_ACCESS: "AmazonElasticFileSystemFullAccess",
  AMAZON_ELASTIC_FILE_SYSTEM_READ_ONLY_ACCESS:
    "AmazonElasticFileSystemReadOnlyAccess",
  AMAZON_ELASTIC_FILE_SYSTEM_SERVICE_ROLE_POLICY:
    "AmazonElasticFileSystemServiceRolePolicy",
  AMAZON_ELASTIC_MAP_REDUCE_EDITORS_ROLE: "AmazonElasticMapReduceEditorsRole",
  AMAZON_ELASTIC_MAP_REDUCE_FULL_ACCESS: "AmazonElasticMapReduceFullAccess",
  AMAZON_ELASTIC_MAP_REDUCE_READ_ONLY_ACCESS:
    "AmazonElasticMapReduceReadOnlyAccess",
  AMAZON_ELASTIC_MAP_REDUCE_ROLE: "AmazonElasticMapReduceRole",
  AMAZON_ELASTIC_MAP_REDUCE_FOR_AUTO_SCALING_ROLE:
    "AmazonElasticMapReduceforAutoScalingRole",
  AMAZON_ELASTIC_MAP_REDUCE_FOR_EC2_ROLE: "AmazonElasticMapReduceforEC2Role",
  AMAZON_ELASTIC_TRANSCODER_ROLE: "AmazonElasticTranscoderRole",
  AMAZON_ELASTIC_TRANSCODER_FULL_ACCESS: "AmazonElasticTranscoder_FullAccess",
  AMAZON_ELASTIC_TRANSCODER_JOBS_SUBMITTER:
    "AmazonElasticTranscoder_JobsSubmitter",
  AMAZON_ELASTIC_TRANSCODER_READ_ONLY_ACCESS:
    "AmazonElasticTranscoder_ReadOnlyAccess",
  AMAZON_ELASTICSEARCH_SERVICE_ROLE_POLICY:
    "AmazonElasticsearchServiceRolePolicy",
  AMAZON_EVENT_BRIDGE_FULL_ACCESS: "AmazonEventBridgeFullAccess",
  AMAZON_EVENT_BRIDGE_READ_ONLY_ACCESS: "AmazonEventBridgeReadOnlyAccess",
  AMAZON_F_SX_CONSOLE_FULL_ACCESS: "AmazonFSxConsoleFullAccess",
  AMAZON_F_SX_CONSOLE_READ_ONLY_ACCESS: "AmazonFSxConsoleReadOnlyAccess",
  AMAZON_F_SX_FULL_ACCESS: "AmazonFSxFullAccess",
  AMAZON_F_SX_READ_ONLY_ACCESS: "AmazonFSxReadOnlyAccess",
  AMAZON_F_SX_SERVICE_ROLE_POLICY: "AmazonFSxServiceRolePolicy",
  AMAZON_FORECAST_FULL_ACCESS: "AmazonForecastFullAccess",
  AMAZON_FREE_RTOS_FULL_ACCESS: "AmazonFreeRTOSFullAccess",
  AMAZON_FREE_RTOS_OTA_UPDATE: "AmazonFreeRTOSOTAUpdate",
  AMAZON_GLACIER_FULL_ACCESS: "AmazonGlacierFullAccess",
  AMAZON_GLACIER_READ_ONLY_ACCESS: "AmazonGlacierReadOnlyAccess",
  AMAZON_GUARD_DUTY_FULL_ACCESS: "AmazonGuardDutyFullAccess",
  AMAZON_GUARD_DUTY_READ_ONLY_ACCESS: "AmazonGuardDutyReadOnlyAccess",
  AMAZON_GUARD_DUTY_SERVICE_ROLE_POLICY: "AmazonGuardDutyServiceRolePolicy",
  AMAZON_INSPECTOR_FULL_ACCESS: "AmazonInspectorFullAccess",
  AMAZON_INSPECTOR_READ_ONLY_ACCESS: "AmazonInspectorReadOnlyAccess",
  AMAZON_INSPECTOR_SERVICE_ROLE_POLICY: "AmazonInspectorServiceRolePolicy",
  AMAZON_KINESIS_ANALYTICS_FULL_ACCESS: "AmazonKinesisAnalyticsFullAccess",
  AMAZON_KINESIS_ANALYTICS_READ_ONLY: "AmazonKinesisAnalyticsReadOnly",
  AMAZON_KINESIS_FIREHOSE_FULL_ACCESS: "AmazonKinesisFirehoseFullAccess",
  AMAZON_KINESIS_FIREHOSE_READ_ONLY_ACCESS:
    "AmazonKinesisFirehoseReadOnlyAccess",
  AMAZON_KINESIS_FULL_ACCESS: "AmazonKinesisFullAccess",
  AMAZON_KINESIS_READ_ONLY_ACCESS: "AmazonKinesisReadOnlyAccess",
  AMAZON_KINESIS_VIDEO_STREAMS_FULL_ACCESS:
    "AmazonKinesisVideoStreamsFullAccess",
  AMAZON_KINESIS_VIDEO_STREAMS_READ_ONLY_ACCESS:
    "AmazonKinesisVideoStreamsReadOnlyAccess",
  AMAZON_LAUNCH_WIZARD_FULL_ACCESS: "AmazonLaunchWizardFullaccess",
  AMAZON_LEX_FULL_ACCESS: "AmazonLexFullAccess",
  AMAZON_LEX_READ_ONLY: "AmazonLexReadOnly",
  AMAZON_LEX_RUN_BOTS_ONLY: "AmazonLexRunBotsOnly",
  AMAZON_MQ_API_FULL_ACCESS: "AmazonMQApiFullAccess",
  AMAZON_MQ_API_READ_ONLY_ACCESS: "AmazonMQApiReadOnlyAccess",
  AMAZON_MQ_FULL_ACCESS: "AmazonMQFullAccess",
  AMAZON_MQ_READ_ONLY_ACCESS: "AmazonMQReadOnlyAccess",
  AMAZON_MSK_FULL_ACCESS: "AmazonMSKFullAccess",
  AMAZON_MSK_READ_ONLY_ACCESS: "AmazonMSKReadOnlyAccess",
  AMAZON_MACHINE_LEARNING_BATCH_PREDICTIONS_ACCESS:
    "AmazonMachineLearningBatchPredictionsAccess",
  AMAZON_MACHINE_LEARNING_CREATE_ONLY_ACCESS:
    "AmazonMachineLearningCreateOnlyAccess",
  AMAZON_MACHINE_LEARNING_FULL_ACCESS: "AmazonMachineLearningFullAccess",
  AMAZON_MACHINE_LEARNING_MANAGE_REAL_TIME_ENDPOINT_ONLY_ACCESS:
    "AmazonMachineLearningManageRealTimeEndpointOnlyAccess",
  AMAZON_MACHINE_LEARNING_READ_ONLY_ACCESS:
    "AmazonMachineLearningReadOnlyAccess",
  AMAZON_MACHINE_LEARNING_REAL_TIME_PREDICTION_ONLY_ACCESS:
    "AmazonMachineLearningRealTimePredictionOnlyAccess",
  AMAZON_MACHINE_LEARNING_ROLE_FOR_REDSHIFT_DATA_SOURCE_V2:
    "AmazonMachineLearningRoleforRedshiftDataSourceV2",
  AMAZON_MACIE_FULL_ACCESS: "AmazonMacieFullAccess",
  AMAZON_MACIE_HANDSHAKE_ROLE: "AmazonMacieHandshakeRole",
  AMAZON_MACIE_SERVICE_ROLE: "AmazonMacieServiceRole",
  AMAZON_MACIE_SERVICE_ROLE_POLICY: "AmazonMacieServiceRolePolicy",
  AMAZON_MACIE_SETUP_ROLE: "AmazonMacieSetupRole",
  AMAZON_MANAGED_BLOCKCHAIN_CONSOLE_FULL_ACCESS:
    "AmazonManagedBlockchainConsoleFullAccess",
  AMAZON_MANAGED_BLOCKCHAIN_FULL_ACCESS: "AmazonManagedBlockchainFullAccess",
  AMAZON_MANAGED_BLOCKCHAIN_READ_ONLY_ACCESS:
    "AmazonManagedBlockchainReadOnlyAccess",
  AMAZON_MECHANICAL_TURK_FULL_ACCESS: "AmazonMechanicalTurkFullAccess",
  AMAZON_MECHANICAL_TURK_READ_ONLY: "AmazonMechanicalTurkReadOnly",
  AMAZON_MOBILE_ANALYTICS_FINANCIAL_REPORT_ACCESS:
    "AmazonMobileAnalyticsFinancialReportAccess",
  AMAZON_MOBILE_ANALYTICS_FULL_ACCESS: "AmazonMobileAnalyticsFullAccess",
  AMAZON_MOBILE_ANALYTICS_NON_FINANCIAL_REPORT_ACCESS:
    "AmazonMobileAnalyticsNon-financialReportAccess",
  AMAZON_MOBILE_ANALYTICS_WRITE_ONLY_ACCESS:
    "AmazonMobileAnalyticsWriteOnlyAccess",
  AMAZON_PERSONALIZE_FULL_ACCESS: "AmazonPersonalizeFullAccess",
  AMAZON_POLLY_FULL_ACCESS: "AmazonPollyFullAccess",
  AMAZON_POLLY_READ_ONLY_ACCESS: "AmazonPollyReadOnlyAccess",
  AMAZON_QLDB_CONSOLE_FULL_ACCESS: "AmazonQLDBConsoleFullAccess",
  AMAZON_QLDB_FULL_ACCESS: "AmazonQLDBFullAccess",
  AMAZON_QLDB_READ_ONLY: "AmazonQLDBReadOnly",
  AMAZON_RDS_BETA_SERVICE_ROLE_POLICY: "AmazonRDSBetaServiceRolePolicy",
  AMAZON_RDS_DATA_FULL_ACCESS: "AmazonRDSDataFullAccess",
  AMAZON_RDS_DIRECTORY_SERVICE_ACCESS: "AmazonRDSDirectoryServiceAccess",
  AMAZON_RDS_ENHANCED_MONITORING_ROLE: "AmazonRDSEnhancedMonitoringRole",
  AMAZON_RDS_FULL_ACCESS: "AmazonRDSFullAccess",
  AMAZON_RDS_PREVIEW_SERVICE_ROLE_POLICY: "AmazonRDSPreviewServiceRolePolicy",
  AMAZON_RDS_READ_ONLY_ACCESS: "AmazonRDSReadOnlyAccess",
  AMAZON_RDS_SERVICE_ROLE_POLICY: "AmazonRDSServiceRolePolicy",
  AMAZON_REDSHIFT_FULL_ACCESS: "AmazonRedshiftFullAccess",
  AMAZON_REDSHIFT_QUERY_EDITOR: "AmazonRedshiftQueryEditor",
  AMAZON_REDSHIFT_READ_ONLY_ACCESS: "AmazonRedshiftReadOnlyAccess",
  AMAZON_REDSHIFT_SERVICE_LINKED_ROLE_POLICY:
    "AmazonRedshiftServiceLinkedRolePolicy",
  AMAZON_REKOGNITION_FULL_ACCESS: "AmazonRekognitionFullAccess",
  AMAZON_REKOGNITION_READ_ONLY_ACCESS: "AmazonRekognitionReadOnlyAccess",
  AMAZON_REKOGNITION_SERVICE_ROLE: "AmazonRekognitionServiceRole",
  AMAZON_ROUTE53_AUTO_NAMING_FULL_ACCESS: "AmazonRoute53AutoNamingFullAccess",
  AMAZON_ROUTE53_AUTO_NAMING_READ_ONLY_ACCESS:
    "AmazonRoute53AutoNamingReadOnlyAccess",
  AMAZON_ROUTE53_AUTO_NAMING_REGISTRANT_ACCESS:
    "AmazonRoute53AutoNamingRegistrantAccess",
  AMAZON_ROUTE53_DOMAINS_FULL_ACCESS: "AmazonRoute53DomainsFullAccess",
  AMAZON_ROUTE53_DOMAINS_READ_ONLY_ACCESS: "AmazonRoute53DomainsReadOnlyAccess",
  AMAZON_ROUTE53_FULL_ACCESS: "AmazonRoute53FullAccess",
  AMAZON_ROUTE53_READ_ONLY_ACCESS: "AmazonRoute53ReadOnlyAccess",
  AMAZON_ROUTE53_RESOLVER_FULL_ACCESS: "AmazonRoute53ResolverFullAccess",
  AMAZON_ROUTE53_RESOLVER_READ_ONLY_ACCESS:
    "AmazonRoute53ResolverReadOnlyAccess",
  AMAZON_S3_FULL_ACCESS: "AmazonS3FullAccess",
  AMAZON_S3_READ_ONLY_ACCESS: "AmazonS3ReadOnlyAccess",
  AMAZON_SES_FULL_ACCESS: "AmazonSESFullAccess",
  AMAZON_SES_READ_ONLY_ACCESS: "AmazonSESReadOnlyAccess",
  AMAZON_SNS_FULL_ACCESS: "AmazonSNSFullAccess",
  AMAZON_SNS_READ_ONLY_ACCESS: "AmazonSNSReadOnlyAccess",
  AMAZON_SNS_ROLE: "AmazonSNSRole",
  AMAZON_SQS_FULL_ACCESS: "AmazonSQSFullAccess",
  AMAZON_SQS_READ_ONLY_ACCESS: "AmazonSQSReadOnlyAccess",
  AMAZON_SSM_AUTOMATION_APPROVER_ACCESS: "AmazonSSMAutomationApproverAccess",
  AMAZON_SSM_AUTOMATION_ROLE: "AmazonSSMAutomationRole",
  AMAZON_SSM_DIRECTORY_SERVICE_ACCESS: "AmazonSSMDirectoryServiceAccess",
  AMAZON_SSM_FULL_ACCESS: "AmazonSSMFullAccess",
  AMAZON_SSM_MAINTENANCE_WINDOW_ROLE: "AmazonSSMMaintenanceWindowRole",
  AMAZON_SSM_MANAGED_INSTANCE_CORE: "AmazonSSMManagedInstanceCore",
  AMAZON_SSM_READ_ONLY_ACCESS: "AmazonSSMReadOnlyAccess",
  AMAZON_SSM_SERVICE_ROLE_POLICY: "AmazonSSMServiceRolePolicy",
  AMAZON_SAGE_MAKER_FULL_ACCESS: "AmazonSageMakerFullAccess",
  AMAZON_SAGE_MAKER_NOTEBOOKS_SERVICE_ROLE_POLICY:
    "AmazonSageMakerNotebooksServiceRolePolicy",
  AMAZON_SAGE_MAKER_READ_ONLY: "AmazonSageMakerReadOnly",
  AMAZON_SUMERIAN_FULL_ACCESS: "AmazonSumerianFullAccess",
  AMAZON_TEXTRACT_FULL_ACCESS: "AmazonTextractFullAccess",
  AMAZON_TEXTRACT_SERVICE_ROLE: "AmazonTextractServiceRole",
  AMAZON_TRANSCRIBE_FULL_ACCESS: "AmazonTranscribeFullAccess",
  AMAZON_TRANSCRIBE_READ_ONLY_ACCESS: "AmazonTranscribeReadOnlyAccess",
  AMAZON_VPC_CROSS_ACCOUNT_NETWORK_INTERFACE_OPERATIONS:
    "AmazonVPCCrossAccountNetworkInterfaceOperations",
  AMAZON_VPC_FULL_ACCESS: "AmazonVPCFullAccess",
  AMAZON_VPC_READ_ONLY_ACCESS: "AmazonVPCReadOnlyAccess",
  AMAZON_WORK_LINK_FULL_ACCESS: "AmazonWorkLinkFullAccess",
  AMAZON_WORK_LINK_READ_ONLY: "AmazonWorkLinkReadOnly",
  AMAZON_WORK_LINK_SERVICE_ROLE_POLICY: "AmazonWorkLinkServiceRolePolicy",
  AMAZON_WORK_MAIL_EVENTS_SERVICE_ROLE_POLICY:
    "AmazonWorkMailEventsServiceRolePolicy",
  AMAZON_WORK_MAIL_FULL_ACCESS: "AmazonWorkMailFullAccess",
  AMAZON_WORK_MAIL_READ_ONLY_ACCESS: "AmazonWorkMailReadOnlyAccess",
  AMAZON_WORK_SPACES_ADMIN: "AmazonWorkSpacesAdmin",
  AMAZON_WORK_SPACES_APPLICATION_MANAGER_ADMIN_ACCESS:
    "AmazonWorkSpacesApplicationManagerAdminAccess",
  AMAZON_WORK_SPACES_SELF_SERVICE_ACCESS: "AmazonWorkSpacesSelfServiceAccess",
  AMAZON_WORK_SPACES_SERVICE_ACCESS: "AmazonWorkSpacesServiceAccess",
  AMAZON_ZOCALO_FULL_ACCESS: "AmazonZocaloFullAccess",
  AMAZON_ZOCALO_READ_ONLY_ACCESS: "AmazonZocaloReadOnlyAccess",
  APPLICATION_AUTO_SCALING_FOR_AMAZON_APP_STREAM_ACCESS:
    "ApplicationAutoScalingForAmazonAppStreamAccess",
  APPLICATION_DISCOVERY_SERVICE_CONTINUOUS_EXPORT_SERVICE_ROLE_POLICY:
    "ApplicationDiscoveryServiceContinuousExportServiceRolePolicy",
  AUTO_SCALING_CONSOLE_FULL_ACCESS: "AutoScalingConsoleFullAccess",
  AUTO_SCALING_CONSOLE_READ_ONLY_ACCESS: "AutoScalingConsoleReadOnlyAccess",
  AUTO_SCALING_FULL_ACCESS: "AutoScalingFullAccess",
  AUTO_SCALING_NOTIFICATION_ACCESS_ROLE: "AutoScalingNotificationAccessRole",
  AUTO_SCALING_READ_ONLY_ACCESS: "AutoScalingReadOnlyAccess",
  AUTO_SCALING_SERVICE_ROLE_POLICY: "AutoScalingServiceRolePolicy",
  BILLING: "Billing",
  CLIENT_VPN_SERVICE_ROLE_POLICY: "ClientVPNServiceRolePolicy",
  CLOUD_FRONT_FULL_ACCESS: "CloudFrontFullAccess",
  CLOUD_FRONT_READ_ONLY_ACCESS: "CloudFrontReadOnlyAccess",
  CLOUD_HSM_SERVICE_ROLE_POLICY: "CloudHSMServiceRolePolicy",
  CLOUD_SEARCH_FULL_ACCESS: "CloudSearchFullAccess",
  CLOUD_SEARCH_READ_ONLY_ACCESS: "CloudSearchReadOnlyAccess",
  CLOUD_TRAIL_SERVICE_ROLE_POLICY: "CloudTrailServiceRolePolicy",
  CLOUD_WATCH_CROSS_ACCOUNT_ACCESS: "CloudWatch-CrossAccountAccess",
  CLOUD_WATCH_ACTIONS_EC2_ACCESS: "CloudWatchActionsEC2Access",
  CLOUD_WATCH_AGENT_ADMIN_POLICY: "CloudWatchAgentAdminPolicy",
  CLOUD_WATCH_AGENT_SERVER_POLICY: "CloudWatchAgentServerPolicy",
  CLOUD_WATCH_AUTOMATIC_DASHBOARDS_ACCESS:
    "CloudWatchAutomaticDashboardsAccess",
  CLOUD_WATCH_EVENTS_BUILT_IN_TARGET_EXECUTION_ACCESS:
    "CloudWatchEventsBuiltInTargetExecutionAccess",
  CLOUD_WATCH_EVENTS_FULL_ACCESS: "CloudWatchEventsFullAccess",
  CLOUD_WATCH_EVENTS_INVOCATION_ACCESS: "CloudWatchEventsInvocationAccess",
  CLOUD_WATCH_EVENTS_READ_ONLY_ACCESS: "CloudWatchEventsReadOnlyAccess",
  CLOUD_WATCH_EVENTS_SERVICE_ROLE_POLICY: "CloudWatchEventsServiceRolePolicy",
  CLOUD_WATCH_FULL_ACCESS: "CloudWatchFullAccess",
  CLOUD_WATCH_LOGS_FULL_ACCESS: "CloudWatchLogsFullAccess",
  CLOUD_WATCH_LOGS_READ_ONLY_ACCESS: "CloudWatchLogsReadOnlyAccess",
  CLOUD_WATCH_READ_ONLY_ACCESS: "CloudWatchReadOnlyAccess",
  CLOUDWATCH_APPLICATION_INSIGHTS_SERVICE_LINKED_ROLE_POLICY:
    "CloudwatchApplicationInsightsServiceLinkedRolePolicy",
  COMPREHEND_DATA_ACCESS_ROLE_POLICY: "ComprehendDataAccessRolePolicy",
  COMPREHEND_FULL_ACCESS: "ComprehendFullAccess",
  COMPREHEND_MEDICAL_FULL_ACCESS: "ComprehendMedicalFullAccess",
  COMPREHEND_READ_ONLY: "ComprehendReadOnly",
  CONFIG_CONFORMS_SERVICE_ROLE_POLICY: "ConfigConformsServiceRolePolicy",
  DAX_SERVICE_ROLE_POLICY: "DAXServiceRolePolicy",
  DATA_SCIENTIST: "DataScientist",
  DATABASE_ADMINISTRATOR: "DatabaseAdministrator",
  DYNAMO_DB_CLOUD_WATCH_CONTRIBUTOR_INSIGHTS_SERVICE_ROLE_POLICY:
    "DynamoDBCloudWatchContributorInsightsServiceRolePolicy",
  DYNAMO_DB_REPLICATION_SERVICE_ROLE_POLICY:
    "DynamoDBReplicationServiceRolePolicy",
  EC2_INSTANCE_CONNECT: "EC2InstanceConnect",
  ELASTI_CACHE_SERVICE_ROLE_POLICY: "ElastiCacheServiceRolePolicy",
  ELASTIC_LOAD_BALANCING_FULL_ACCESS: "ElasticLoadBalancingFullAccess",
  ELASTIC_LOAD_BALANCING_READ_ONLY: "ElasticLoadBalancingReadOnly",
  ELEMENTAL_APPLIANCES_SOFTWARE_FULL_ACCESS:
    "ElementalAppliancesSoftwareFullAccess",
  FMS_SERVICE_ROLE_POLICY: "FMSServiceRolePolicy",
  F_SX_DELETE_SERVICE_LINKED_ROLE_ACCESS: "FSxDeleteServiceLinkedRoleAccess",
  GLOBAL_ACCELERATOR_FULL_ACCESS: "GlobalAcceleratorFullAccess",
  GLOBAL_ACCELERATOR_READ_ONLY_ACCESS: "GlobalAcceleratorReadOnlyAccess",
  GREENGRASS_OTA_UPDATE_ARTIFACT_ACCESS: "GreengrassOTAUpdateArtifactAccess",
  IAM_ACCESS_ADVISOR_READ_ONLY: "IAMAccessAdvisorReadOnly",
  IAM_FULL_ACCESS: "IAMFullAccess",
  IAM_READ_ONLY_ACCESS: "IAMReadOnlyAccess",
  IAM_SELF_MANAGE_SERVICE_SPECIFIC_CREDENTIALS:
    "IAMSelfManageServiceSpecificCredentials",
  IAM_USER_CHANGE_PASSWORD: "IAMUserChangePassword",
  IAM_USER_SSH_KEYS: "IAMUserSSHKeys",
  KAFKA_SERVICE_ROLE_POLICY: "KafkaServiceRolePolicy",
  LAKE_FORMATION_DATA_ACCESS_SERVICE_ROLE_POLICY:
    "LakeFormationDataAccessServiceRolePolicy",
  LEX_BOT_POLICY: "LexBotPolicy",
  LEX_CHANNEL_POLICY: "LexChannelPolicy",
  LIGHTSAIL_EXPORT_ACCESS: "LightsailExportAccess",
  MIGRATION_HUB_DMS_ACCESS_SERVICE_ROLE_POLICY:
    "MigrationHubDMSAccessServiceRolePolicy",
  MIGRATION_HUB_SMS_ACCESS_SERVICE_ROLE_POLICY:
    "MigrationHubSMSAccessServiceRolePolicy",
  MIGRATION_HUB_SERVICE_ROLE_POLICY: "MigrationHubServiceRolePolicy",
  NEPTUNE_CONSOLE_FULL_ACCESS: "NeptuneConsoleFullAccess",
  NEPTUNE_FULL_ACCESS: "NeptuneFullAccess",
  NEPTUNE_READ_ONLY_ACCESS: "NeptuneReadOnlyAccess",
  NETWORK_ADMINISTRATOR: "NetworkAdministrator",
  POWER_USER_ACCESS: "PowerUserAccess",
  QUICK_SIGHT_ACCESS_FOR_S3_STORAGE_MANAGEMENT_ANALYTICS_READ_ONLY:
    "QuickSightAccessForS3StorageManagementAnalyticsReadOnly",
  RDS_CLOUD_HSM_AUTHORIZATION_ROLE: "RDSCloudHsmAuthorizationRole",
  READ_ONLY_ACCESS: "ReadOnlyAccess",
  RESOURCE_GROUPS_AND_TAG_EDITOR_FULL_ACCESS:
    "ResourceGroupsandTagEditorFullAccess",
  RESOURCE_GROUPS_AND_TAG_EDITOR_READ_ONLY_ACCESS:
    "ResourceGroupsandTagEditorReadOnlyAccess",
  SECRETS_MANAGER_READ_WRITE: "SecretsManagerReadWrite",
  SECURITY_AUDIT: "SecurityAudit",
  SERVER_MIGRATION_CONNECTOR: "ServerMigrationConnector",
  SERVER_MIGRATION_SERVICE_LAUNCH_ROLE: "ServerMigrationServiceLaunchRole",
  SERVER_MIGRATION_SERVICE_ROLE: "ServerMigrationServiceRole",
  SERVICE_QUOTAS_FULL_ACCESS: "ServiceQuotasFullAccess",
  SERVICE_QUOTAS_READ_ONLY_ACCESS: "ServiceQuotasReadOnlyAccess",
  SERVICE_QUOTAS_SERVICE_ROLE_POLICY: "ServiceQuotasServiceRolePolicy",
  SIMPLE_WORKFLOW_FULL_ACCESS: "SimpleWorkflowFullAccess",
  SUPPORT_USER: "SupportUser",
  SYSTEM_ADMINISTRATOR: "SystemAdministrator",
  TAG_POLICIES_SERVICE_ROLE_POLICY: "TagPoliciesServiceRolePolicy",
  TRANSLATE_FULL_ACCESS: "TranslateFullAccess",
  TRANSLATE_READ_ONLY: "TranslateReadOnly",
  VM_IMPORT_EXPORT_ROLE_FOR_AWS_CONNECTOR: "VMImportExportRoleForAWSConnector",
  VIEW_ONLY_ACCESS: "ViewOnlyAccess",
  WAF_LOGGING_SERVICE_ROLE_POLICY: "WAFLoggingServiceRolePolicy",
  WAF_REGIONAL_LOGGING_SERVICE_ROLE_POLICY:
    "WAFRegionalLoggingServiceRolePolicy",
  WAF_V2_LOGGING_SERVICE_ROLE_POLICY: "WAFV2LoggingServiceRolePolicy",
  WELL_ARCHITECTED_CONSOLE_FULL_ACCESS: "WellArchitectedConsoleFullAccess",
  WELL_ARCHITECTED_CONSOLE_READ_ONLY_ACCESS:
    "WellArchitectedConsoleReadOnlyAccess",
  WORK_LINK_SERVICE_ROLE_POLICY: "WorkLinkServiceRolePolicy",
};
